[Remap]
x = x
y = y
z = z
a = a
b = b
c = c
s = s

;-| Default Values |-------------------------------------------------------
[Defaults]
command.time = 15
command.buffer.time = 1


;-| AI用コマンド |--------------------------------------------------------
[Command]
name = "AI0"
command = a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a
time = 0
[Command]
name = "AI1"
command = b,b,b,b,b,b,b,b,b,b,b,b,b,b,b,b,b,b,b
time = 0
[Command]
name = "AI2"
command = c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c
time = 0
[Command]
name = "AI3"
command = x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x
time = 0
[Command]
name = "AI4"
command = y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y
time = 0
[Command]
name = "AI5"
command = z,z,z,z,z,z,z,z,z,z,z,z,z,z,z,z,z,z,z
time = 0
[Command]
name = "AI6"
command = s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s
time = 0
[Command]
name = "AI7"
command = F,F,F,F,F,F,F,F,F,F,F,F,F,F,F,F,F,F,F
time = 0
[Command]
name = "AI8"
command = D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D
time = 0
[Command]
name = "AI9"
command = B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B
time = 0
[Command]
name = "AI10"
command = U,U,U,U,U,U,U,U,U,U,U,U,U,U,U,U,U,U,U
time = 0
[Command]
name = "AI11"
command = a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a
time = 0
[Command]
name = "AI12"
command = c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c
time = 0
[Command]
name = "AI13"
command = x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x
time = 0
[Command]
name = "AI14"
command = y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y
time = 0
[Command]
name = "AI15"
command = z,z,z,z,z,z,z,z,z,z,z,z,z,z,z,z,z,z,z
time = 0
[Command]
name = "AI16"
command = s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s
time = 0
[Command]
name = "AI17"
command = a,B,c,x,y,z,s,B,D,F,U,a,b,c,x,y,z,s,s
time = 0
[Command]
name = "AI18"
command = a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a
time = 0
[Command]
name = "AI19"
command = b,b,b,b,b,b,b,b,b,b,b,b,b,b,b,b,b,b,b
time = 0
[Command]
name = "AI20"
command = c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c
time = 0
[Command]
name = "AI21"
command = x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x
time = 0
[Command]
name = "AI22"
command = y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y
time = 0
[Command]
name = "AI23"
command = z,z,z,z,z,z,z,z,z,z,z,z,z,z,z,z,z,z,z
time = 0
[Command]
name = "AI24"
command = s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s
time = 0
[Command]
name = "AI25"
command = F,F,F,F,F,F,F,F,F,F,F,F,F,F,F,F,F,F,F
time = 0
[Command]
name = "AI26"
command = D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D
time = 0
[Command]
name = "AI27"
command = B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B
time = 0
[Command]
name = "AI28"
command = U,U,U,U,U,U,U,U,U,U,U,U,U,U,U,U,U,U,U
time = 0
[Command]
name = "AI29"
command = a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a
time = 0
[Command]
name = "AI30"
command = c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c
time = 0
[Command]
name = "AI31"
command = x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x
time = 0
[Command]
name = "AI32"
command = y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y,y
time = 0
[Command]
name = "AI33"
command = z,z,z,z,z,z,z,z,z,z,z,z,z,z,z,z,z,z,z
time = 0
[Command]
name = "AI34"
command = s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s
time = 0
[Command]
name = "AI35"
command = z,z,z,z,z,z,z,z,z,z,z,z,z,z,z,z,z,z,z
time = 0
[Command]
name = "AI36"
command = z,z,z,z,z,z,a,a,a,z,z,z,z,z,z,z,z,z,z
time = 0
[Command]
name = "AI37"
command = z,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,z,z,z
time = 0
[Command]
name = "AI38"
command = z,z,z,z,z,a,a,a,z,z,z,z,z,a,a,a,z,z,z
time = 0
[Command]
name = "AI39"
command = z,z,z,z,z,a,a,a,z,z,z,z,z,z,a,a,z,z,z
time = 0
[Command]
name = "AI40"
command = z,z,z,z,a,a,a,z,z,z,z,a,z,z,a,a,z,z,z
time = 0
[Command]
name = "AI41"
command = z,z,z,a,z,z,z,z,z,z,z,z,z,a,a,z,z,z,z
time = 0
[Command]
name = "AI42"
command = z,z,z,z,z,z,z,z,z,z,z,z,z,z,z,z,z,z,z
time = 0
[Command]
name = "AI43"
command = z,z,z,z,z,z,z,z,z,z,z,z,z,z,z,z,a,a,z
time = 0
[Command]
name = "AI44"
command = z,z,a,a,a,a,z,z,z,z,z,z,z,z,z,a,a,a,z
time = 0
[Command]
name = "AI45"
command = z,z,z,z,z,z,a,a,z,z,z,z,z,a,a,a,a,z,z
time = 0
[Command]
name = "AI46"
command = z,z,z,z,z,z,z,z,a,a,a,a,a,a,z,z,z,z,z
time = 0
[Command]
name = "AI47"
command = z,z,z,a,a,a,a,z,z,z,z,z,z,z,z,z,z,z,z
time = 0
[Command]
name = "AI48"
command = z,z,z,z,z,a,a,a,z,z,z,a,a,a,z,z,a,z,a
time = 0
[Command]
name = "AI49"
command = z,z,z,z,a,a,a,z,z,z,z,z,a,a,a,z,z,z,z
time = 0
[Command]
name = "AI50"
command = z,z,z,a,a,z,z,z,z,z,z,z,z,z,a,a,z,z,z
time = 0
[Command]
name = "AI51"
command = x,x,x,x,x,x,x,a,x,x,a,x,x,x,x,x,x,x,x
time = 0
[Command]
name = "AI52"
command = y,y,y,y,y,b,a,y,y,y,y,y,y,y,y,y,y,y,y
time = 0
[Command]
name = "AI53"
command = z,z,z,z,z,c,z,c,z,z,z,z,z,z,z,z,z,z,z
time = 0
[Command]
name = "AI54"
command = s,s,s,s,c,s,a,s,s,s,s,s,s,s,s,s,s,s,s
time = 0
[Command]
name = "AI55"
command = z,z,z,z,x,z,z,y,z,z,z,z,z,z,z,z,z,z,z
time = 0
[Command]
name = "AI56"
command = z,a,z,a,z,z,a,a,a,z,z,z,z,b,z,z,z,z,z
time = 0
[Command]
name = "AI57"
command = z,a,a,a,a,b,c,a,a,a,a,a,a,a,a,a,z,z,z
time = 0
[Command]
name = "AI58"
command = z,z,z,z,z,a,a,a,z,c,c,z,z,a,a,a,z,z,z
time = 0
[Command]
name = "AI59"
command = z,z,z,z,z,a,a,a,z,b,b,z,z,z,a,a,z,z,z
time = 0



;-| Super Motions |--------------------------------------------------------
[Command]
name = "Super1"
command = ~D, F, D, F, x
time = 32

[Command]
name = "Super1"
command = ~D, DF, D, F, x
time = 32

[Command]
name = "Super1"
command = ~D, F, D, DF, x
time = 32

[Command]
name = "Super2"
command = ~D, F, D, F, y
time = 32

[Command]
name = "Super2"
command = ~D, DF, D, F, y
time = 32

[Command]
name = "Super2"
command = ~D, F, D, DF, y
time = 32

[Command]
name = "Super3"
command = ~D, B, D, B, x
time = 32

[Command]
name = "Super3"
command = ~D, DB, D, B, x
time = 32

[Command]
name = "Super3"
command = ~D, B, D, DB, x
time = 32

[Command]
name = "Super3"
command = ~D, B, D, B, y
time = 32

[Command]
name = "Super3"
command = ~D, DB, D, B, y
time = 32

[Command]
name = "Super3"
command = ~D, B, D, DB, y
time = 32


;-| Special Motions |------------------------------------------------------
[Command]
name = "upper_x"
command = ~F, D, DF, x
time = 26

[Command]
name = "upper_y"
command = ~F, D, F, y
time = 26

[Command]
name = "upper_x"
command = ~F, D, F, x
time = 26

[Command]
name = "upper_y"
command = ~F, D, F, y
time = 26

[Command]
name = "upper_x"
command = ~F, DF, F, x
time = 26

[Command]
name = "upper_y"
command = ~F, DF, F, y
time = 26

[Command]
name = "step"
command = ~D, B, a
time = 23

[Command]
name = "step2"
command = ~D, B, b

[Command]
name = "QCF_x"
command = ~D, F, x

[Command]
name = "QCF_y"
command = ~D, F, y

[Command]
name = "warp"
command = ~D, F, a

[Command]
name = "warp"
command = ~DF, F, a

[Command]
name = "warp2"
command = ~D, F, b

[Command]
name = "warp2"
command = ~DF, F, b

[Command]
name = "QCB_x"
command = ~D, DB, B, x

[Command]
name = "QCB_y"
command = ~D, DB, B, y

[Command]
name = "QCB_xy"
command = ~D, DB, B, x+y

[Command]
name = "FF_ab"
command = F, F, a+b

[Command]
name = "FF_a"
command = F, F, a

[Command]
name = "FF_b"
command = F, F, b

;-| Double Tap |-----------------------------------------------------------
[Command]
name = "FF"     ;Required (do not remove)
command = F, F
time = 10

[Command]
name = "BB"     ;Required (do not remove)
command = B, B
time = 10

;-| 2/3 Button Combination |-----------------------------------------------
[Command]
name = "recovery";Required (do not remove)
command = x+y
time = 1

[Command]
name = "xa";Required (do not remove)
command = x+a
time = 1


;-| Dir + Button |---------------------------------------------------------
[Command]
name = "down_a"
command = /$D,a
time = 1

[Command]
name = "down_b"
command = /$D,b
time = 1

[Command]
name = "HJ"
command = ~$D,UF

;-| Single Button |---------------------------------------------------------
[Command]
name = "a"
command = a
time = 1

[Command]
name = "b"
command = b
time = 1

[Command]
name = "c"
command = c
time = 1

[Command]
name = "x"
command = x
time = 1

[Command]
name = "y"
command = y
time = 1

[Command]
name = "z"
command = z
time = 1

[Command]
name = "start"
command = s
time = 1

;-| Hold Dir |--------------------------------------------------------------
[Command]
name = "holdfwd";Required (do not remove)
command = /$F
time = 1

[Command]
name = "holdback";Required (do not remove)
command = /$B
time = 1

[Command]
name = "holdup" ;Required (do not remove)
command = /$U
time = 1

[Command]
name = "holddown";Required (do not remove)
command = /$D
time = 1


[Statedef -1]

;===========================================================================
[State -1,2]
type = Varset
triggerall = var(18) != 0
triggerall = var(20) != 1
trigger1 = command = "AI1"
trigger2 = command = "AI2"
trigger3 = command = "AI3"
trigger4 = command = "AI4"
trigger5 = command = "AI5"
trigger6 = command = "AI6"
trigger7 = command = "AI7"
trigger8 = command = "AI8"
trigger9 = command = "AI9"
trigger10 = command = "AI10"
trigger11 = command = "AI11"
trigger12 = command = "AI12"
trigger13 = command = "AI13"
trigger14 = command = "AI14"
trigger15 = command = "AI15"
trigger16 = command = "AI16"
trigger17 = command = "AI17"
trigger18 = command = "AI18"
trigger19 = command = "AI19"
trigger20 = command = "AI20"
trigger21 = command = "AI21"
trigger22 = command = "AI22"
trigger23 = command = "AI23"
trigger24 = command = "AI24"
trigger25 = command = "AI25"
trigger26 = command = "AI26"
trigger27 = command = "AI27"
trigger28 = command = "AI28"
trigger29 = command = "AI29"
trigger30 = command = "AI30"
trigger31 = command = "AI31"
trigger32 = command = "AI32"
trigger33 = command = "AI33"
trigger34 = command = "AI34"
trigger35 = command = "AI35"
trigger36 = command = "AI36"
trigger37 = command = "AI37"
trigger38 = command = "AI38"
trigger39 = command = "AI39"
trigger40 = command = "AI40"
trigger41 = command = "AI41"
trigger42 = command = "AI42"
trigger43 = command = "AI43"
trigger44 = command = "AI44"
trigger45 = command = "AI45"
trigger46 = command = "AI46"
trigger47 = command = "AI47"
trigger48 = command = "AI48"
trigger49 = command = "AI49"
trigger50 = command = "AI50"
trigger51 = command = "AI51"
trigger52 = command = "AI52"
trigger53 = command = "AI53"
trigger54 = command = "AI54"
trigger55 = command = "AI55"
trigger56 = command = "AI56"
trigger57 = command = "AI57"
trigger58 = command = "AI58"
trigger59 = command = "AI59"
v = 20
value = 1

[State -1,2]
type = Varset
triggerall = var(18) = 0
triggerall = var(20) = 1
trigger1 = command = "AI1"
trigger2 = command = "AI2"
trigger3 = command = "AI3"
trigger4 = command = "AI4"
trigger5 = command = "AI5"
trigger6 = command = "AI6"
trigger7 = command = "AI7"
trigger8 = command = "AI8"
trigger9 = command = "AI9"
trigger10 = command = "AI10"
trigger11 = command = "AI11"
trigger12 = command = "AI12"
trigger13 = command = "AI13"
trigger14 = command = "AI14"
trigger15 = command = "AI15"
trigger16 = command = "AI16"
trigger17 = command = "AI17"
trigger18 = command = "AI18"
trigger19 = command = "AI19"
trigger20 = command = "AI20"
trigger21 = command = "AI21"
trigger22 = command = "AI22"
trigger23 = command = "AI23"
trigger24 = command = "AI24"
trigger25 = command = "AI25"
trigger26 = command = "AI26"
trigger27 = command = "AI27"
trigger28 = command = "AI28"
trigger29 = command = "AI29"
trigger30 = command = "AI30"
trigger31 = command = "AI31"
trigger32 = command = "AI32"
trigger33 = command = "AI33"
trigger34 = command = "AI34"
trigger35 = command = "AI35"
trigger36 = command = "AI36"
trigger37 = command = "AI37"
trigger38 = command = "AI38"
trigger39 = command = "AI39"
trigger40 = command = "AI40"
trigger41 = command = "AI41"
trigger42 = command = "AI42"
trigger43 = command = "AI43"
trigger44 = command = "AI44"
trigger45 = command = "AI45"
trigger46 = command = "AI46"
trigger47 = command = "AI47"
trigger48 = command = "AI48"
trigger49 = command = "AI49"
trigger50 = command = "AI50"
trigger51 = command = "AI51"
trigger52 = command = "AI52"
trigger53 = command = "AI53"
trigger54 = command = "AI54"
trigger55 = command = "AI55"
trigger56 = command = "AI56"
trigger57 = command = "AI57"
trigger58 = command = "AI58"
trigger59 = command = "AI59"
v = 20
value = 0

;===========================================================================

;-----------AIの行動　ガード(仮) --------
[State -1, AI1];ガード
Type = ChangeState
Value = 120
triggerall = alive = 1
triggerall = IsHelper = 0
TriggerAll = Ctrl
triggerAll = var(20) = 1
triggerAll = movetype != A
TriggerAll = InGuardDist
Trigger1 = var(18) = 4
Trigger1 = var(21) = [0,5]
Trigger2 = var(18) = 3
Trigger2 = var(21) = [0,4]
Trigger3 = var(18) = 2
Trigger3 = var(21) = [0,2]


[State -1, AI2];ガード
Type = ChangeState
Value = 120
triggerall = alive = 1
triggerall = IsHelper = 0
TriggerAll = stateno = 2025
triggerAll = var(20) = 1
triggerAll = movetype != A
triggerAll = movetype != H
TriggerAll = InGuardDist
Trigger1 = var(18) = 4
Trigger1 = var(21) = [0,5]
Trigger2 = var(18) = 3
Trigger2 = var(21) = [0,4]
Trigger3 = var(18) = 2
Trigger3 = var(21) = [0,2]

[State -1, AI3];ガード
Type = ChangeState
Value = 120
triggerall = alive = 1
triggerall = IsHelper = 0
TriggerAll = stateno = 2026
triggerAll = var(20) = 1
triggerAll = movetype != A
triggerAll = movetype != H
TriggerAll = InGuardDist
Trigger1 = var(18) = 4
Trigger1 = var(21) = [0,5]
Trigger2 = var(18) = 3
Trigger2 = var(21) = [0,4]
Trigger3 = var(18) = 2
Trigger3 = var(21) = [0,2]

;-----------AIの行動 噴水ヒット後 --------
;技がヒットしたときのコンボ行動全般

;var22=1で近距離ルミナ
;var22=2で遠距離ルミナ
;var22=3で遠トリップ
;var22=4で弱ピジョン>ルミナス
;var22=5で強ピジョン>トリップ

[State -1, AI4];画面端でヒット、弱ピジョン＞ルミナス連続技へ
type = varset
Triggerall = var(18) = [2,4]
trigger1 = ProjHitTime(3060) = 5
trigger1 = FrontEdgeBodyDist = [70,130]
trigger1 = p2dist X = [40,140]
trigger1 = p2movetype = H
trigger1 = enemy,pos Y = [-25,0]
trigger1 = var(22) = 0
v = 22
value = 4

;（近距離）
[State -1, AI5];地上付近、近距離ヒット、弱ルミナスへ
type = varset
trigger1 = ProjHitTime(3060) = 5
trigger1 = p2bodydist X = [2,60]
trigger1 = p2movetype = H
trigger1 = enemy,pos Y = [-25,0]
trigger1 = var(22) = 0
v = 22
value = 1
;
[State -1, AI6];空中、近距離ヒット、強ルミナスへ
type = varset
trigger1 = ProjHitTime(3060) = 5
trigger1 = p2movetype = H
trigger1 = p2bodydist X = [2,60]
trigger1 = enemy,pos Y = [-90,-25]
trigger1 = var(22) = 0
v = 22
value = 2

;（中距離）
[State -1, AI7];地上付近、中距離ヒット、強ルミナスへ
type = varset
trigger1 = ProjHitTime(3060) = 5
trigger1 = p2bodydist X = [61,90]
trigger1 = p2movetype = H
trigger1 = enemy,pos Y = [-25,0]
trigger1 = var(22) = 0
v = 22
value = 2
;
[State -1, AI8];空中、近距離ヒット、トリップへ
type = varset
trigger1 = ProjHitTime(3060) = 6
trigger1 = p2movetype = H
trigger1 = p2bodydist X = [61,90]
trigger1 = enemy,pos Y = [-90,-25]
trigger1 = var(22) = 0
v = 22
value = 3

;（遠距離）
[State -1, AI9];地上付近、遠距離ヒット、強ルミナスへ
type = varset
trigger1 = ProjHitTime(3060) = 5
trigger1 = p2bodydist X = [90,120]
trigger1 = p2movetype = H
trigger1 = enemy,pos Y = [-25,0]
trigger1 = var(22) = 0
v = 22
value = 2
;（遠距離）
[State -1, AI10];地上付近、遠距離ヒット、強ルミナスへ
type = varset
trigger1 = ProjHitTime(3060) = 5
trigger1 = p2bodydist X = [90,120]
trigger1 = p2movetype = H
trigger1 = enemy,pos Y = [-90,-25]
trigger1 = var(22) = 0
v = 22
value = 5

[State -1, AI11];ルミナステップ高位置ヒットによる変数の変更
type = varset
trigger1 = stateno = 1420
trigger1 = p2dist Y = [-40,-20]
trigger1 = movehit = 1
v = 22
value = 10
[State -1, AI12];ルミナステップ高位置ヒットによる変数の変更
type = varset
trigger1 = stateno = 1420
trigger1 = p2dist Y = [-70,-41]
trigger1 = movehit = 1
v = 22
value = 11
[State -1, AI13];ルミナステップ高位置ヒットによる変数の変更
type = varset
trigger1 = stateno = 1420
trigger1 = p2dist Y = [-90,-71]
trigger1 = movehit = 1
v = 22
value = 12
[State -1, AI14];ルミナステップ高位置ヒットによる変数の変更
type = varset
trigger1 = stateno = 1420
trigger1 = p2dist Y = [-150,-91]
trigger1 = movehit = 1
v = 22
value = 13
[State -1, AI15];ルミナステップヒットによる変数の変更
type = varset
trigger1 = stateno = 1420
trigger1 = movehit = 0
trigger1 = animtime = 0
v = 22
value = 0

[State -1, AI16]
type = varset
trigger1 = movetype = H
v = 22
value = 0

;高位置ルミナステップヒット時
[State -1, AI17]
type = ChangeState
value = 75
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = var(22) = [10,15]
triggerall = statetype != A
triggerall = stateno = 1420
triggerall = animtime = 0
;triggerall = p2statetype = A
triggerall = p2movetype = H
;triggerall = p2dist X = [-20,40]
trigger1 = 1;var(21) = 5
[State -1, AI18]
type = ChangeState
value = 210
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = var(22) = 10
triggerall = statetype != A
triggerall = stateno = 75
triggerall = time = 2
;triggerall = p2statetype = A
triggerall = p2movetype = H
;triggerall = p2dist X = [-20,40]
trigger1 = 1;var(21) = 5
[State -1, AI19]
type = ChangeState
value = 210
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = var(22) = 11
triggerall = statetype != A
triggerall = stateno = 75
triggerall = time = 8
;triggerall = p2statetype = A
triggerall = p2movetype = H
;triggerall = p2dist X = [-20,40]
trigger1 = 1;var(21) = 5
[State -1, AI20]
type = ChangeState
value = 210
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = var(22) = 12
triggerall = statetype != A
triggerall = stateno = 75
triggerall = time = 12
;triggerall = p2statetype = A
triggerall = p2movetype = H
;triggerall = p2dist X = [-20,40]
trigger1 = 1;var(21) = 5
[State -1, AI21]
type = ChangeState
value = 210
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = var(22) = 13
triggerall = statetype != A
triggerall = stateno = 75
triggerall = time = 16
;triggerall = p2statetype = A
triggerall = p2movetype = H
;triggerall = p2dist X = [-20,40]
trigger1 = 1;var(21) = 5
[State -1, AI22]
type = ChangeState
value = 1300
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = var(22) = [10,15]
triggerall = statetype != A
triggerall = stateno = 210
triggerall = movehit
;triggerall = p2statetype = A
triggerall = p2movetype = H
;triggerall = p2dist X = [-20,40]
trigger1 = 1;var(21) = 5

;近距離スプラッシュ→弱ルミナ
[State -1, AI23]
type = ChangeState
value = 1400
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = var(22) = 1
triggerall = statetype != A
triggerall = ctrl
;triggerall = p2statetype = A
triggerall = p2movetype = H
;triggerall = p2bodydist X = [6,65]
trigger1 = 1;var(21) = 5

;画面端スプラッシュ→弱ピジョン→強ルミナス
[State -1, AI24]
type = ChangeState
value = 1450
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = var(22) = 4
triggerall = statetype != A
triggerall = stateno = 1100
triggerall = animtime = 0
;triggerall = p2statetype = A
triggerall = p2movetype = H
trigger1 = 1
[State -1, AI25]
type = ChangeState
value = 1100
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(32) = 0
triggerall = var(20) = 1
triggerall = var(22) = 4
triggerall = statetype != A
triggerall = ctrl
;triggerall = p2statetype = A
triggerall = p2movetype = H
trigger1 = 1;var(21) = 5


;中距離スプラッシュ→強ルミナ
[State -1, AI26]
type = ChangeState
value = 1450
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = var(22) = 2
triggerall = statetype != A
triggerall = stateno = 75
triggerall = time = 4
triggerall = p2statetype = A
triggerall = p2movetype = H
trigger1 = 1;var(21) = 5
[State -1, AI27]
type = ChangeState
value = 1450
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = var(22) = 2
triggerall = statetype != A
triggerall = ctrl
triggerall = p2statetype = A
triggerall = p2movetype = H
trigger1 = 1;var(21) = 5

;遠距離上空スプラッシュ→ピジョン→トリップ
[State -1, AI28]
type = ChangeState
value = 1205
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = var(22) = 5
triggerall = statetype != A
triggerall = ctrl
triggerall = animtime = 0
triggerall = p2statetype = A
triggerall = p2movetype = H
trigger1 = 1;var(21) = 5

;
[State -1, AI29]
type = ChangeState
value = 1205
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = var(22) = 3
triggerall = statetype != A
triggerall = ctrl
triggerall = p2statetype = A
triggerall = p2movetype = H
trigger1 = 1;var(21) = 5
[State -1, AI30]
type = ChangeState
value = 640
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = var(22) = 3
triggerall = statetype = A
triggerall = stateno = 1210
triggerall = time > 7
triggerall = p2statetype = A
triggerall = p2movetype = H
trigger1 = 1;var(21) = 5

[State -1, AI31];足払いヒット時にときどき出す
type = ChangeState
value = 3000
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = NumHelper(3015) != 0
triggerall = var(20) = 1
triggerall = power >= 1000
triggerall = statetype != A
triggerall = p2movetype = H
triggerall = stateno = 440
triggerall = movehit = 6
trigger1 = var(21) = 1
trigger1 = p2dist X= [20,60]

[State -1, AI32];
type = ChangeState
value = 3005
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = NumHelper(3015) = 0
triggerall = var(20) = 1
triggerall = power >= 1000
triggerall = statetype != A
triggerall = ctrl
triggerall = FrontEdgeBodyDist = [104,125]
triggerall = p2dist X = [40,140]
triggerall = enemy,pos Y = [-25,0]
trigger1 = var(18) = [2,4]
trigger1 = var(21) = [0,3]
trigger2 = var(18) = 1
trigger2 = var(21) = 0


;-----------AIの行動 スプラッシュ --------
[State -1, AI33];足払いヒット時にときどき出す
type = ChangeState
value = 3000
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = power >= 2000
triggerall = var(20) = 1
triggerall = statetype != A
triggerall = p2movetype = H
triggerall = stateno = 440
triggerall = movehit = 6
triggerall = p2dist X= [20,60]
trigger1 = var(18) = [2,4]
trigger1 = var(21) = [1,2]


[State -1, AI34];ジャンプ飛び込みに反応
type = ChangeState
value = 3000
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = power >= 1000
triggerall = var(20) = 1
triggerall = statetype != A
triggerall = p2movetype != H
triggerall = ctrl
triggerall = p2statetype = A
triggerall = p2dist X= [130,180]
triggerall = enemy,vel X = [0,3.7]
Trigger1 = var(18) = [3,4]
trigger1 = var(21) = [0,3]
Trigger2 = var(18) = 2
trigger2 = var(21) = [0,1]
Trigger3 = var(18) = 1
trigger3 = var(21) = 0
[State -1, AI35];ジャンプ飛び込みに反応
type = ChangeState
value = 3000
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = power >= 1000
triggerall = var(20) = 1
triggerall = statetype != A
triggerall = p2movetype != H
triggerall = ctrl
triggerall = p2statetype = A
triggerall = p2dist X= [180,225]
triggerall = enemy,vel X = [3.7,4.4]
Trigger1 = var(18) = [3,4]
trigger1 = var(21) = [0,3]
Trigger2 = var(18) = 2
trigger2 = var(21) = [0,1]
Trigger3 = var(18) = 1
trigger3 = var(21) = 0

[State -1, AI36];ジャンプに反応
type = ChangeState
value = 3000
Triggerall = var(18) = [3,4]
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = power >= 1000
triggerall = var(20) = 1
triggerall = statetype != A
triggerall = p2movetype != H
triggerall = ctrl
triggerall = p2statetype != A
triggerall = enemy,stateno = 40
triggerall = enemy,sysvar(1) = 0
triggerall = p2dist X= [80,105]
Trigger1 = var(18) = [3,4]
trigger1 = var(21) = [0,2]
Trigger2 = var(18) = 2
trigger2 = var(21) = [0,1]

[State -1, AI37];ジャンプ飛び込みに反応
type = ChangeState
value = 3000
Triggerall = var(18) = [3,4]
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = power >= 1000
triggerall = var(20) = 1
triggerall = statetype != A
triggerall = p2movetype != H
triggerall = ctrl
triggerall = p2statetype != A
triggerall = enemy,stateno = 40
triggerall = enemy,sysvar(1) = 1
triggerall = p2dist X= [130,180]
Trigger1 = var(18) = [3,4]
trigger1 = var(21) = [0,3]
Trigger2 = var(18) = 2
trigger2 = var(21) = 0

[State -1, AI38];ジャンプ飛び込みに反応
type = ChangeState
value = 3005
Triggerall = var(18) = [3,4]
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = power >= 1000
triggerall = var(20) = 1
triggerall = statetype != A
triggerall = p2movetype != H
triggerall = ctrl
triggerall = p2statetype != A
triggerall = enemy,stateno = 40
triggerall = enemy,sysvar(1) = 1
triggerall = p2dist X= [180,230]
Trigger1 = var(18) = [3,4]
trigger1 = var(21) = [0,2]
Trigger2 = var(18) = 2
trigger2 = var(21) = 0

[State -1, AI39]
type = ChangeState
value = 3005
Triggerall = var(18) = [3,4]
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = power >= 1000
triggerall = var(20) = 1
triggerall = statetype != A
triggerall = p2statetype = A
triggerall = p2movetype != H
triggerall = ctrl
trigger1 = var(21) = [0,3]
trigger1 = p2dist X= [190,210]
trigger1 = enemy,time < 4
trigger1 = enemy,vel X = [0,3.7]
trigger1 = enemy,vel Y < 0

[State -1, AI40];ジャンプ飛び込みに反応
type = ChangeState
value = 3000
Triggerall = var(18) = [1,2]
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = power >= 1000
triggerall = var(20) = 1
triggerall = statetype != A
triggerall = p2movetype != H
triggerall = ctrl
trigger1 = p2statetype = A
trigger1 = var(21) = [0,1]
trigger1 = p2dist X= [130,180]
trigger1 = enemy,vel X = [0,3.7]
trigger2 = p2statetype = A
trigger2 = var(21) = [0,1]
trigger2 = p2dist X= [180,200]
trigger2 = enemy,vel X = [3.7,5.4]
trigger3 = p2statetype != A
trigger3 = enemy,stateno = 40
trigger3 = enemy,sysvar(1) = 1
trigger3 = var(21) = [0,1]

[State -1, AI41]
type = ChangeState
value = 3005
Triggerall = var(18) = [1,2]
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = power >= 1000
triggerall = var(20) = 1
triggerall = statetype != A
triggerall = p2statetype = A
triggerall = p2movetype != H
triggerall = ctrl
trigger1 = var(21) = [0,1]
trigger1 = p2dist X= [190,210]
trigger1 = enemy,time < 4
trigger1 = enemy,vel X = [0,3.7]
trigger1 = enemy,vel Y < 0

;-----------AIの行動 対空/割り込み -------

[State -1, AI42];地上での割り込み
type = ChangeState
value = 1300
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = stateno = 2025
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = statetype != A
triggerall = p2statetype != A
triggerall = p2movetype = A
triggerall = enemy,time < 4
triggerall = p2bodydist X = [0,33]
trigger1 = var(18) = 4
trigger1 = var(21) = [0,5]
trigger2 = var(18) = 3
trigger2 = var(21) = [0,4]
trigger3 = var(18) = 2
trigger3 = var(21) = [0,2]
trigger4 = var(18) = 1
trigger4 = var(21) = 5

[State -1, AI43];地上での割り込み
type = ChangeState
value = 1300
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = ctrl
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = statetype != A
triggerall = p2statetype != A
triggerall = p2movetype = A
triggerall = enemy,time < 4
triggerall = p2bodydist X = [0,16]
trigger1 = var(18) = 4
trigger1 = var(21) = [0,5]
trigger2 = var(18) = 3
trigger2 = var(21) = [0,4]
trigger3 = var(18) = 2
trigger3 = var(21) = [0,2]
trigger4 = var(18) = 1
trigger4 = var(21) = 5

[State -1, AI44];飛び込みを迎撃(相手がこっちに飛んでいる)
type = ChangeState
value = 1300
triggerall = var(18) = [3,4]
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = statetype != A
triggerall = p2statetype = A
triggerall = enemynear,vel X >= 2
triggerall = p2bodydist X = [-15,40]
triggerall = p2dist Y = [-73,-45]
trigger1 = ctrl
trigger1 = var(21) = [0,5]
trigger2 = stateno = 2025
trigger2 = var(21) = [0,5]
trigger3 = stateno = 2026
trigger3 = var(21) = [0,5]
[State -1, AI45];飛び込みを迎撃(相手が垂直に飛んでいる)
type = ChangeState
value = 1300
triggerall = var(18) = [3,4]
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = ctrl
triggerall = statetype != A
triggerall = p2statetype = A
triggerall = enemynear,vel X >= 0
triggerall = enemynear,vel X < 2
triggerall = p2bodydist X = [-15,30]
trigger1ll = p2dist Y = [-73,-35]
trigger1 = ctrl
trigger1 = var(21) = [0,5]
trigger2 = stateno = 2025
trigger2 = var(21) = [0,5]
trigger3 = stateno = 2026
trigger3 = var(21) = [0,5]
[State -1, AI46];飛び込みを迎撃(相手がこっちに飛んでいる)
type = ChangeState
value = 1300
triggerall = var(18) = 2
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = statetype != A
triggerall = p2statetype = A
triggerall = enemynear,vel X >= 2
triggerall = p2bodydist X = [-15,40]
triggerall = p2dist Y = [-73,-45]
trigger1 = ctrl
trigger1 = var(21) = [3,5]
trigger2 = stateno = 2025
trigger2 = var(21) = [3,5]
trigger3 = stateno = 2026
trigger3 = var(21) = [3,5]
[State -1, AI47];飛び込みを迎撃(相手が垂直に飛んでいる)
type = ChangeState
value = 1300
triggerall = var(18) = 2
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = ctrl
triggerall = statetype != A
triggerall = p2statetype = A
triggerall = enemynear,vel X >= 0
triggerall = enemynear,vel X < 2
triggerall = p2bodydist X = [-15,30]
trigger1ll = p2dist Y = [-73,-35]
trigger1 = ctrl
trigger1 = var(21) = [3,5]
trigger2 = stateno = 2025
trigger2 = var(21) = [3,5]
trigger3 = stateno = 2026
trigger3 = var(21) = [3,5]
[State -1, AI48];飛び込みを迎撃(相手がこっちに飛んでいる)
type = ChangeState
value = 1300
triggerall = var(18) = 1
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = statetype != A
triggerall = p2statetype = A
triggerall = enemynear,vel X >= 2
triggerall = p2bodydist X = [-15,40]
triggerall = p2dist Y = [-73,-45]
trigger1 = ctrl
trigger1 = var(21) = 0
trigger2 = stateno = 2025
trigger2 = var(21) = 0
trigger3 = stateno = 2026
trigger3 = var(21) = 0
[State -1, AI49];飛び込みを迎撃(相手が垂直に飛んでいる)
type = ChangeState
value = 1300
triggerall = var(18) = 1
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = ctrl
triggerall = statetype != A
triggerall = p2statetype = A
triggerall = enemynear,vel X >= 0
triggerall = enemynear,vel X < 2
triggerall = p2bodydist X = [-15,30]
trigger1ll = p2dist Y = [-73,-35]
trigger1 = ctrl
trigger1 = var(21) = 0
trigger2 = stateno = 2025
trigger2 = var(21) = 0
trigger3 = stateno = 2026
trigger3 = var(21) = 0

[State -1, AI50];近距離での前方ジャンプを迎撃
type = ChangeState
value = 410
triggerall = var(18) = 4
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = statetype != A
triggerall = p2statetype = A
triggerall = enemynear,vel X >= 2
triggerall = p2bodydist X = [-3,20]
triggerall = p2dist Y = [-73,-5]
trigger1 = ctrl
trigger1 = var(21) = [0,5]
trigger2 = stateno = 2025
trigger2 = var(21) = [0,5]
trigger3 = stateno = 2026
trigger3 = var(21) = [0,5]
[State -1, AI51];近距離での垂直ジャンプを迎撃
type = ChangeState
value = 410
triggerall = var(18) = 4
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = statetype != A
triggerall = p2statetype = A
triggerall = enemynear,vel X = 0
triggerall = p2movetype != H
triggerall = p2bodydist X = [-3,20]
triggerall = p2dist Y = [-73,-5]
trigger1 = ctrl
trigger1 = var(21) = [0,5]
trigger2 = stateno = 2025
trigger2 = var(21) = [0,5]
trigger3 = stateno = 2026
trigger3 = var(21) = [0,5]
[State -1, AI52];近距離での前方ジャンプを迎撃
type = ChangeState
value = 410
triggerall = var(18) = 3
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = statetype != A
triggerall = p2statetype = A
triggerall = enemynear,vel X >= 2
triggerall = p2bodydist X = [-3,20]
triggerall = p2dist Y = [-73,-5]
trigger1 = ctrl
trigger1 = var(21) = [0,4]
trigger2 = stateno = 2025
trigger2 = var(21) = [0,4]
trigger3 = stateno = 2026
trigger3 = var(21) = [0,4]
[State -1, AI53];近距離での垂直ジャンプを迎撃
type = ChangeState
value = 410
triggerall = var(18) = 3
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = statetype != A
triggerall = p2statetype = A
triggerall = enemynear,vel X = 0
triggerall = p2movetype != H
triggerall = p2bodydist X = [-3,20]
triggerall = p2dist Y = [-73,-5]
trigger1 = ctrl
trigger1 = var(21) = [0,4]
trigger2 = stateno = 2025
trigger2 = var(21) = [0,4]
trigger3 = stateno = 2026
trigger3 = var(21) = [0,4]
[State -1, AI54];近距離での前方ジャンプを迎撃
type = ChangeState
value = 410
triggerall = var(18) = 2
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = statetype != A
triggerall = p2statetype = A
triggerall = enemynear,vel X >= 2
triggerall = p2bodydist X = [-3,20]
triggerall = p2dist Y = [-73,-5]
trigger1 = ctrl
trigger1 = var(21) = [0,2]
trigger2 = stateno = 2025
trigger2 = var(21) = [0,1]
trigger3 = stateno = 2026
trigger3 = var(21) = [0,1]
[State -1, AI55];近距離での垂直ジャンプを迎撃
type = ChangeState
value = 410
triggerall = var(18) = 2
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = statetype != A
triggerall = p2statetype = A
triggerall = enemynear,vel X = 0
triggerall = p2movetype != H
triggerall = p2bodydist X = [-3,20]
triggerall = p2dist Y = [-73,-5]
trigger1 = ctrl
trigger1 = var(21) = [0,2]
trigger2 = stateno = 2025
trigger2 = var(21) = [0,1]
trigger3 = stateno = 2026
trigger3 = var(21) = [0,1]
[State -1, AI56];近距離での前方ジャンプを迎撃
type = ChangeState
value = 410
triggerall = var(18) = 1
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = statetype != A
triggerall = p2statetype = A
triggerall = enemynear,vel X >= 2
triggerall = p2bodydist X = [-3,20]
triggerall = p2dist Y = [-73,-5]
trigger1 = ctrl
trigger1 = var(21) = 0
[State -1, AI57];近距離での垂直ジャンプを迎撃
type = ChangeState
value = 410
triggerall = var(18) = 1
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = statetype != A
triggerall = p2statetype = A
triggerall = enemynear,vel X = 0
triggerall = p2movetype != H
triggerall = p2bodydist X = [-3,20]
triggerall = p2dist Y = [-73,-5]
trigger1 = ctrl
trigger1 = var(21) = 0

[State -1, AI58]
type = ChangeState
value = 410
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = ctrl
triggerall = statetype != A
triggerall = p2statetype = A
triggerall = p2bodydist X <= 16
triggerall = p2bodydist Y = [-70,-15]
trigger1 = var(18) = 4
trigger1 = var(21) = [0,5]
trigger2 = var(18) = 3
trigger2 = var(21) = [0,4]
trigger3 = var(18) = 2
trigger3 = var(21) = [0,1]
trigger4 = var(18) = 1
trigger4 = var(21) = 0

;-----------AIの行動 トリップの出現後 -------
[State -1, AI59];弱K
type = ChangeState
value = 630
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = statetype = A
triggerall = stateno = 1210
triggerall = time > 7
triggerall = time = 8
trigger1 = p2bodydist X = [-5,5]
trigger1 = enemy,vel X >= 0
trigger1 = p2dist Y = [10,150]
trigger1 = var(21) = [0,1]

[State -1, AI60];強K
type = ChangeState
value = 640
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = statetype = A
triggerall = stateno = 1210
triggerall = time > 7
triggerall = time = 9
triggerall = p2bodydist X = [-10,10]
triggerall = enemy,vel X >= 0
triggerall = p2dist Y = [10,150]
trigger1 = var(18) = [3,4]
trigger1 = var(21) = [0,5]
trigger2 = var(18) = 2
trigger2 = var(21) = [0,4]
trigger3 = var(18) = 1
trigger3 = var(21) = 0

[State -1, AI61];ラビット
type = ChangeState
value = 1150
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = statetype = A
triggerall = stateno = 1210
triggerall = time > 7
triggerall = time = 8
triggerall = var(34) = 0
trigger1 = p2bodydist X = [10,40]
trigger1 = enemy,vel X >= 0
trigger1 = p2dist Y = [10,150]
trigger1 = var(21) = [0,1]

[State -1, AI62];P
type = ChangeState
value = 600
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = statetype = A
triggerall = stateno = 1210
triggerall = time > 7
triggerall = time = 9
triggerall = p2bodydist X = [10,40]
triggerall = enemy,vel X >= 0
triggerall = p2dist Y = [-20,150]
trigger1 = var(18) = [3,4]
trigger1 = var(21) = [2,5]
trigger2 = var(18) = 2
trigger2 = var(21) = [2,4]
trigger3 = var(18) = 1
trigger3 = var(21) = 2

[State -1, AI63];ラビット
type = ChangeState
value = 1160
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = statetype = A
triggerall = stateno = 1210
triggerall = time > 7
triggerall = time = 8
triggerall = var(34) = 0
triggerall = p2bodydist X = [41,100]
triggerall = p2dist Y = [10,150]
trigger1 = var(18) = [2,4]
trigger1 = var(21) = [0,1]

[State -1, AI64];二段ジャンプ
type = ChangeState
value = 70
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = statetype = A
triggerall = stateno = 1210
triggerall = time > 7
triggerall = time = 11
triggerall = var(34) = 0
triggerall = p2bodydist X = [41,135]
triggerall = p2dist Y = [10,150]
trigger1 = var(18) = [2,4]
trigger1 = var(21) = [1,5]
trigger2 = var(18) = 1
trigger2 = var(21) = [1,3]

[State -1, AI65];強P
type = ChangeState
value = 610
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = statetype = A
triggerall = stateno = 1210
triggerall = time > 7
triggerall = time = 8
triggerall = var(34) = 0
triggerall = p2bodydist X = [41,100]
triggerall = enemy,vel X > 0
triggerall = p2dist Y = [-30,150]
trigger1 = var(18) = [3,4]
trigger1 = var(21) = [0,5]
trigger2 = var(18) = 2
trigger2 = var(21) = [0,4]
trigger3 = var(18) = 1
trigger3 = var(21) = [0,2]

;-----------AIの行動 空ジャンプstate70 ------
[State -1, AI66];強K
type = ChangeState
value = 640
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = stateno = 71
triggerall = var(20) = 1
triggerall = statetype = A
triggerall = p2statetype = A
triggerall = pos Y < -82
triggerall = time <= 29
triggerall = p2bodydist X = [-10,28]
triggerall = enemy,vel X >= 0
triggerall = p2dist Y = [20,90]
trigger1 = var(18) = [3,4]
trigger1 = var(21) = [0,5]
trigger2 = var(18) = 2
trigger2 = var(21) = [0,2]
trigger3 = var(18) = 1
trigger3 = var(21) = 0

[State -1, AI67];強P
type = ChangeState
value = 610
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = stateno = 71
triggerall = var(20) = 1
triggerall = statetype = A
triggerall = p2statetype = A
triggerall = pos Y < -82
triggerall = time < 29
triggerall = p2bodydist X = [-10,28]
triggerall = vel X > 0
triggerall = enemy,vel X >= 0
triggerall = p2dist Y = [-20,19]
trigger1 = var(18) = [3,4]
trigger1 = var(21) = [0,5]
trigger2 = var(18) = 2
trigger2 = var(21) = [0,2]
trigger3 = var(18) = 1
trigger3 = var(21) = 0

[State -1, AI68];強P
type = ChangeState
value = 610
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = stateno = 71
triggerall = var(20) = 1
triggerall = statetype = A
triggerall = p2statetype = A
triggerall = pos Y < -42
triggerall = vel Y < 4.6
triggerall = time > 29
triggerall = p2bodydist X = [40,65]
triggerall = vel X > 0
triggerall = enemy,vel X >= 0
triggerall = p2dist Y = [-20,30]
trigger1 = var(18) = [3,4]
trigger1 = var(21) = [0,5]
trigger2 = var(18) = 2
trigger2 = var(21) = [0,2]
trigger3 = var(18) = 1
trigger3 = var(21) = 0

[State -1, AI69];強P
type = ChangeState
value = 610
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = stateno = 71
triggerall = var(20) = 1
triggerall = statetype = A
triggerall = p2statetype = A
triggerall = pos Y < -42
triggerall = vel Y < 4.6
triggerall = time > 29
triggerall = p2bodydist X = [40,65]
triggerall = vel X > 0
triggerall = enemy,vel X >= 0
triggerall = p2dist Y = [-20,30]
triggerall = vel Y < 5.6
triggerall = time < 80
triggerall = p2bodydist X = [8,35]
triggerall = p2dist Y = [-20,30]
triggerall = vel X >= 0
triggerall = enemy,vel X >= 0
trigger1 = var(18) = [3,4]
trigger1 = var(21) = [0,5]
trigger2 = var(18) = 2
trigger2 = var(21) = [0,2]
trigger3 = var(18) = 1
trigger3 = var(21) = 0

[State -1, AI70];弱K
type = ChangeState
value = 630
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = stateno = 71
triggerall = var(20) = 1
triggerall = statetype = A
triggerall = p2statetype = A
triggerall = pos Y < -52
trigger2 = vel Y < 4.6
trigger1 = p2bodydist X = [0,72]
trigger1 = vel X > 0
trigger1 = enemy,vel X > 0
trigger1 = p2dist Y = [7,40]
trigger2 = vel Y < 4.6
trigger2 = p2bodydist X = [0,25]
trigger2 = vel X > 0
trigger2 = enemy,vel X = 0
trigger2 = p2dist Y = [7,40]

[State -1, AI71];強パンチ
type = ChangeState
value = 610
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = statetype = A
triggerall = p2statetype != A
triggerall = pos Y < -30
triggerall = stateno = 71
trigger1 = time = [8,11]
trigger1 = vel X > 0
trigger1 = p2bodydist X = [43,78]
trigger1 = var(23) = 0
trigger1 = var(21) = [0,2]
trigger2 = time = [9,23]
trigger2 = vel X > 0
trigger2 = p2bodydist X = [43,78]
trigger2 = var(23) = 1
trigger2 = var(21) = [0,2]
[State -1, AI72];強パンチ
type = ChangeState
value = 610
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = statetype = A
triggerall = p2statetype != A
triggerall = pos Y < -30
triggerall = stateno = 71
triggerall = time = [9,23]
triggerall = vel X > 0
triggerall = p2bodydist X = [78,93]
trigger1 = var(18) = [3,4]
trigger1 = var(21) = [0,5]
trigger2 = var(18) = 2
trigger2 = var(21) = [0,2]
trigger3 = var(18) = 1
trigger3 = var(21) = 0

[State -1, AI73];弱パンチ
type = ChangeState
value = 600
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = statetype = A
triggerall = p2statetype != A
triggerall = pos Y < -30
triggerall = stateno = 71
triggerall = time = [23,31]
triggerall = vel X > 0
triggerall = p2bodydist X = [93,105]
trigger1 = var(18) = [3,4]
trigger1 = var(21) = [0,5]
trigger2 = var(18) = 2
trigger2 = var(21) = [0,2]
trigger3 = var(18) = 1
trigger3 = var(21) = 0

[State -1, AI74];強キック
type = ChangeState
value = 640
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = statetype = A
triggerall = p2statetype != A
triggerall = pos Y < -30
triggerall = stateno = 71
triggerall = time = [8,11]
triggerall = vel X > 0
triggerall = p2bodydist X = [43,78]
trigger1 = var(21) = 2

[State -1, AI75];弱キック
type = ChangeState
value = 630
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = statetype = A
triggerall = p2statetype != A
triggerall = pos Y < -30
triggerall = stateno = 71
trigger1 = time = [8,11]
trigger1 = vel X > 0
trigger1 = p2bodydist X = [43,78]
trigger1 = var(23) = 0
trigger1 = var(21) = [3,5]
[State -1, AI76];弱キック
type = ChangeState
value = 1500
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = stateno = 630
triggerall = var(20) = 1
triggerall = statetype = A
triggerall = p2statetype != A
triggerall = pos Y < -15
triggerall = movehit = 1
triggerall = vel X >= 0
triggerall = p2bodydist X = [0,48]
trigger1 = var(23) = 0
trigger1 = var(18) != 1

[State -1, AI77];強キック
type = ChangeState
value = 640
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = statetype = A
triggerall = p2statetype != A
triggerall = pos Y < -50
triggerall = time = [24,26]
triggerall = stateno = 71
triggerall = p2bodydist X = [-10,50]
triggerall = vel X > 0
trigger1 = var(18) = [3,4]
trigger1 = var(21) = [0,5]
trigger2 = var(18) = 2
trigger2 = var(21) = [0,2]
trigger3 = var(18) = 1
trigger3 = var(21) = 0

[State -1, AI78];強キック
type = ChangeState
value = 640
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = statetype = A
triggerall = p2statetype != A
triggerall = pos Y < -50
triggerall = time = [24,26]
triggerall = stateno = 71
triggerall = p2bodydist X = [-10,33]
triggerall = vel X = 0
trigger1 = var(18) = [3,4]
trigger1 = var(21) = [0,5]
trigger2 = var(18) = 2
trigger2 = var(21) = [0,2]
trigger3 = var(18) = 1
trigger3 = var(21) = 0

[State -1, AI79];強キック
type = ChangeState
value = 640
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = statetype = A
triggerall = p2statetype != A
triggerall = pos Y < -52
triggerall = time = [30,33]
triggerall = stateno = 71
trigger1 = p2bodydist X = [-10,50]
trigger1 = vel X = 0
trigger1 = var(23) = 1

[State -1, AI80];オーロラスライド（足元狙い）
type = ChangeState
value = 1500
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = statetype = A
triggerall = p2statetype != A
triggerall = stateno = 71
trigger1 = vel Y < 4
trigger1 = pos Y = [-64,-55]
trigger1 = p2bodydist X = [40,53]
trigger1 = var(21) = [0,4]
trigger2 = vel Y < 4
trigger2 = pos Y = [-74,-65]
trigger2 = p2bodydist X = [46,59]
trigger2 = var(21) = [0,4]

[State -1, AI81];オーロラスライド（めくり狙い）
type = ChangeState
value = 1500
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = statetype = A
triggerall = p2statetype != A
triggerall = pos Y < -68
triggerall = stateno = 71
triggerall = p2bodydist X <= 3
triggerall = p2bodydist X >= 0
trigger1 = var(21) = [0,2]

;-----------AIの行動 ジャンプ中の動作 -------
;自分が空中
;相手も空中

[State -1, AI82];強K
type = ChangeState
value = 640
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = ctrl
triggerall = var(20) = 1
triggerall = statetype = A
triggerall = p2statetype = A
triggerall = pos Y < -82
triggerall = time < 29
triggerall = p2bodydist X = [-10,28]
triggerall = vel X > 0
triggerall = enemy,vel X >= 0
triggerall = p2dist Y = [20,90]
trigger1 = var(18) = [3,4]
trigger1 = var(21) = [0,5]
trigger2 = var(18) = 2
trigger2 = var(21) = [0,2]
trigger3 = var(18) = 1
trigger3 = var(21) = 0

[State -1, AI83];強P
type = ChangeState
value = 610
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = ctrl
triggerall = var(20) = 1
triggerall = statetype = A
triggerall = p2statetype = A
triggerall = pos Y < -82
triggerall = time < 29
triggerall = p2bodydist X = [-10,28]
triggerall = vel X > 0
triggerall = enemy,vel X >= 0
triggerall = p2dist Y = [-20,19]
trigger1 = var(18) = [3,4]
trigger1 = var(21) = [0,5]
trigger2 = var(18) = 2
trigger2 = var(21) = [0,2]
trigger3 = var(18) = 1
trigger3 = var(21) = 0

[State -1, AI84];強P
type = ChangeState
value = 610
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = ctrl
triggerall = var(20) = 1
triggerall = statetype = A
triggerall = p2statetype = A
triggerall = pos Y < -42
triggerall = vel Y < 4.6
triggerall = time < 29
triggerall = p2bodydist X = [40,65]
triggerall = vel X > 0
triggerall = enemy,vel X >= 0
triggerall = p2dist Y = [-20,30]
trigger1 = var(18) = [3,4]
trigger1 = var(21) = [0,5]
trigger2 = var(18) = 2
trigger2 = var(21) = [0,2]
trigger3 = var(18) = 1
trigger3 = var(21) = 0

[State -1, AI85];強P
type = ChangeState
value = 610
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = ctrl
triggerall = var(20) = 1
triggerall = statetype = A
triggerall = p2statetype = A
triggerall = pos Y < -42
triggerall = vel Y < 5.6
triggerall = time < 80
triggerall = p2bodydist X = [8,35]
triggerall = p2dist Y = [-20,30]
triggerall = vel X >= 0
triggerall = enemy,vel X >= 0
trigger1 = var(18) = [3,4]
trigger1 = var(21) = [0,5]
trigger2 = var(18) = 2
trigger2 = var(21) = [0,2]
trigger3 = var(18) = 1
trigger3 = var(21) = 0

[State -1, AI86];弱P
type = ChangeState
value = 600
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = ctrl
triggerall = var(20) = 1
triggerall = statetype = A
triggerall = p2statetype = A
triggerall = pos Y < -42
trigger1 = vel Y < 4.6
trigger1 = time < 29
trigger1 = p2bodydist X = [50,93]
trigger1 = vel X > 0
trigger1 = enemy,vel X >= 0
trigger1 = p2dist Y = [-18,25]
trigger2 = vel Y < 4.6
trigger2 = time < 29
trigger2 = p2bodydist X = [50,89]
trigger2 = vel X = 0
trigger2 = enemy,vel X > 0
trigger2 = p2dist Y = [-18,25]
trigger3 = vel Y > 4.9
trigger3 = p2bodydist X = [50,89]
trigger3 = vel X > 0
trigger3 = enemy,vel X > 0
trigger3 = p2dist Y = [50,80]
trigger4 = vel Y < 4.6
trigger4 = p2bodydist X = [40,89]
trigger4 = vel X < 0
trigger4 = enemy,vel X > 0
trigger4 = p2dist Y = [-18,25]
;強Pすかし
[State -1, AI87];
type = ChangeState
value = 610
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = var(34) = 0
triggerall = statetype = A
triggerall = movecontact = 0
triggerall = time > 15
triggerall = pos Y < -15
triggerall = stateno = 600
triggerall = ctrl
trigger1 = vel X < 0
trigger1 = var(21) = [3,5]
;ラビット派生
[State -1, AI88];
type = ChangeState
value = 1160
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = var(34) = 0
triggerall = statetype = A
triggerall = time = 23
triggerall = pos Y < -15
triggerall = stateno = 600
triggerall = ctrl
triggerall = vel X < 0
triggerall = var(21) = [0,2]
trigger1 = var(18) = [2,4]

[State -1, AI89];
type = ChangeState
value = 1150
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = var(34) = 0
triggerall = statetype = A
triggerall = time = 23
triggerall = movecontact = [0,30]
triggerall = pos Y < -18
triggerall = stateno = 600
triggerall = ctrl
triggerall = vel X > 0
triggerall = var(21) = [0,3]
trigger1 = var(18) = [2,4]

[State -1, AI90];弱K
type = ChangeState
value = 630
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = ctrl
triggerall = var(20) = 1
triggerall = statetype = A
triggerall = p2statetype = A
triggerall = pos Y < -52
trigger2 = vel Y < 4.6
trigger1 = p2bodydist X = [0,72]
trigger1 = vel X > 0
trigger1 = enemy,vel X > 0
trigger1 = p2dist Y = [7,40]
trigger2 = vel Y < 4.6
trigger2 = p2bodydist X = [0,25]
trigger2 = vel X > 0
trigger2 = enemy,vel X = 0
trigger2 = p2dist Y = [7,40]
[State -1, AI91]
type = ChangeState
value = 1500
triggerall = var(18) != 1
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = stateno = 630
triggerall = var(20) = 1
triggerall = statetype = A
triggerall = p2statetype = A
triggerall = movecontact
triggerall = pos Y < -52
trigger1 = vel X > 0
trigger1 = p2dist Y = [16,58]
trigger1 = p2dist X = [0,30]

;-----------AIの行動 空中同士の追撃 -------
[State -1, AI92];
type = ChangeState
value = 610
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = ctrl
triggerall = var(20) = 1
triggerall = statetype = A
triggerall = p2statetype = A
triggerall = p2movetype = H
triggerall = pos Y < -32
triggerall = p2bodydist X = [-10,38]
triggerall = p2dist Y = [-28,28]
trigger1 = var(18) = [3,4]
trigger1 = var(21) = [0,5]
trigger2 = var(18) = 2
trigger2 = var(21) = [0,4]
trigger3 = var(18) = 1
trigger3 = var(21) = [0,1]

[State -1, AI93];ワープ出現時
type = ChangeState
value = 610
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = stateno = 1210
triggerall = time > 7
triggerall = var(20) = 1
triggerall = statetype = A
triggerall = p2statetype = A
triggerall = p2movetype = H
triggerall = pos Y < -32
trigger1 = p2bodydist X = [-10,38]
trigger1 = p2dist Y = [-28,28]

[State -1, AI94];ＡＩ二段ジャンプ
type = ChangeState
value = 610
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = stateno = 61
triggerall = time > 7
triggerall = var(20) = 1
triggerall = statetype = A
triggerall = p2statetype = A
triggerall = p2movetype = H
triggerall = pos Y < -32
triggerall = p2bodydist X = [-10,38]
triggerall = p2dist Y = [-28,28]
trigger1 = var(18) = [3,4]
trigger1 = var(21) = [0,5]
trigger2 = var(18) = 2
trigger2 = var(21) = [0,4]
trigger3 = var(18) = 1
trigger3 = var(21) = [0,1]

;-----------AIの行動 ジャンプ中の動作 -------
;自分が空中
;相手が地上
;相手にむかってジャンプ中

[State -1, AI95];強パンチ
type = ChangeState
value = 610
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = statetype = A
triggerall = p2statetype != A
triggerall = pos Y < -30
triggerall = ctrl
triggerall = time = [8,11]
triggerall = vel X > 0
triggerall = p2bodydist X = [43,78]
triggerall = var(23) = 0
triggerall = var(21) = [0,1]
trigger1 = var(18) = [3,4]
trigger1 = var(21) = [0,5]
trigger2 = var(18) = 2
trigger2 = var(21) = [0,3]
trigger3 = var(18) = 1
trigger3 = var(21) = [0,1]

[State -1, AI96];強パンチ
type = ChangeState
value = 610
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = statetype = A
triggerall = p2statetype != A
triggerall = pos Y < -30
triggerall = ctrl
triggerall = time = [9,23]
triggerall = vel X > 0
triggerall = p2bodydist X = [43,78]
trigger1 = var(18) = [3,4]
trigger1 = var(21) = [0,5]
trigger2 = var(18) = 2
trigger2 = var(21) = [0,3]
trigger3 = var(18) = 1
trigger3 = var(21) = [0,1]

[State -1, AI97];強パンチ
type = ChangeState
value = 610
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = statetype = A
triggerall = p2statetype != A
triggerall = pos Y < -30
triggerall = ctrl
triggerall = time = [9,23]
triggerall = vel X > 0
triggerall = p2bodydist X = [78,93]
trigger1 = var(18) = [3,4]
trigger1 = var(21) = [0,5]
trigger2 = var(18) = 2
trigger2 = var(21) = [0,3]
trigger3 = var(18) = 1
trigger3 = var(21) = [0,1]

[State -1, AI98];弱パンチ
type = ChangeState
value = 600
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = statetype = A
triggerall = p2statetype != A
triggerall = pos Y < -30
triggerall = ctrl
triggerall = time = [23,31]
triggerall = vel X > 0
triggerall = p2bodydist X = [93,105]
trigger1 = var(18) = [3,4]
trigger1 = var(21) = [0,5]
trigger2 = var(18) = 2
trigger2 = var(21) = [0,3]
trigger3 = var(18) = 1
trigger3 = var(21) = [0,1]

[State -1, AI99];強キック
type = ChangeState
value = 640
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = statetype = A
triggerall = p2statetype != A
triggerall = pos Y < -30
triggerall = ctrl
triggerall = time = [8,13]
triggerall = vel X > 0
triggerall = p2bodydist X = [43,78]
triggerall = var(23) = 0
trigger1 = var(18) = [3,4]
trigger1 = var(21) = [0,5]
trigger2 = var(18) = 2
trigger2 = var(21) = [0,3]
trigger3 = var(18) = 1
trigger3 = var(21) = [0,1]

[State -1, AI100];弱キック
type = ChangeState
value = 630
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = statetype = A
triggerall = p2statetype != A
triggerall = pos Y < -30
triggerall = ctrl
trigger1 = time = [8,11]
trigger1 = vel X > 0
trigger1 = p2bodydist X = [43,78]
trigger1 = var(23) = 0
trigger1 = var(21) = [3,5]

[State -1, AI101];弱キック
type = ChangeState
value = 1500
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = stateno = 630
triggerall = var(20) = 1
triggerall = statetype = A
triggerall = p2statetype != A
triggerall = pos Y < -15
trigger1 = movehit = 1
trigger1 = vel X >= 0
trigger1 = p2bodydist X = [0,48]
trigger1 = var(23) = 0

[State -1, AI102];強キック
type = ChangeState
value = 640
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = statetype = A
triggerall = p2statetype != A
triggerall = pos Y < -50
triggerall = time = [24,26]
triggerall = ctrl
trigger1 = p2bodydist X = [-13,54]
trigger1 = vel X > 0
trigger2 = p2bodydist X = [-10,33]
trigger2 = vel X = 0

[State -1, AI103];強キック
type = ChangeState
value = 640
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = statetype = A
triggerall = p2statetype != A
triggerall = pos Y < -52
triggerall = time = [30,33]
triggerall = ctrl
trigger1 = p2bodydist X = [-10,50]
trigger1 = vel X = 0
trigger1 = var(23) = 1

[State -1, AI104];強キック
type = ChangeState
value = 640
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = statetype = A
triggerall = p2statetype != A
triggerall = pos Y < -50
triggerall = time = [14,26]
triggerall = ctrl
trigger1 = p2bodydist X = [-13,24]
trigger1 = vel X > 0

[State -1, AI105];オーロラスライド（足元狙い）
type = ChangeState
value = 1500
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = statetype = A
triggerall = p2statetype != A
triggerall = ctrl
trigger1 = vel Y < 4
trigger1 = pos Y = [-94,-75]
trigger1 = p2bodydist X = [50,63]
trigger1 = var(21) = [0,4]

[State -1, AI106];オーロラスライド（足元狙い）
type = ChangeState
value = 1500
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = statetype = A
triggerall = p2statetype != A
triggerall = ctrl
trigger1 = vel Y < 4
trigger1 = pos Y = [-64,-55]
trigger1 = p2bodydist X = [40,53]
trigger1 = var(21) = [0,4]
trigger2 = vel Y < 4
trigger2 = pos Y = [-74,-65]
trigger2 = p2bodydist X = [46,59]
trigger2 = var(21) = [0,4]

[State -1, AI107];オーロラスライド（めくり狙い）
type = ChangeState
value = 1500
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = statetype = A
triggerall = p2statetype != A
triggerall = pos Y < -68
triggerall = ctrl
triggerall = p2bodydist X <= 3
triggerall = p2bodydist X >= 0
trigger1 = var(21) = [0,2]

;-----------AIの行動 適当にだす空中技 -------
;振る技がない時にだしてみる
[State -1, AI108];強P
type = ChangeState
value = 610
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = ctrl
triggerall = var(20) = 1
triggerall = statetype = A
trigger1 = time = 8
trigger1 = p2bodydist X = [100,155]
trigger1 = vel X > 0
trigger2 = time = 8
trigger2 = p2bodydist X = [130,175]
trigger2 = vel X < 0

;-----------AIの行動 相手ふっとび時 -------

[State -1, AI109]
type = ChangeState
value = 210
triggerall = alive = 1
triggerall = ctrl
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = statetype != A
triggerall = p2stateno = 5050
triggerall = p2dist Y < -5
triggerall = p2dist Y > -70
triggerall = p2dist X = [5,40]
triggerall = p2movetype = H
trigger1 = var(21) = [0,5]
[State -1, AI110];ステアーズにコンボ
type = ChangeState
value = 1300
triggerall = alive = 1
triggerall = stateno = 210
triggerall = IsHelper = 0
triggerall = movecontact
triggerall = statetype != A
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = statetype != A
triggerall = p2dist Y < -8
triggerall = p2dist X = [1,34]
triggerall = p2movetype = H
trigger1 = var(21) = [0,5]
trigger1 = var(18) != 1

[State -1, AI111]
type = ChangeState
value = 240
triggerall = alive = 1
triggerall = ctrl
triggerall = P2Life != 0
triggerall = IsHelper = 0
triggerall = var(20) = 1
triggerall = statetype != A
triggerall = p2stateno = 5050
triggerall = p2dist Y < -5
triggerall = p2dist Y > -40
triggerall = p2dist X = [5,85]
triggerall = p2movetype = H
trigger1 = var(21) = [0,5]
[State -1, AI112];画面端ではさらにステアーズにコンボ
type = ChangeState
value = 1300
triggerall = alive = 1
triggerall = stateno = 240
triggerall = movecontact
triggerall = IsHelper = 0
triggerall = statetype != A
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = statetype != A
triggerall = p2dist Y < -5
triggerall = p2dist X = [5,30]
triggerall = p2movetype = H
trigger1 = var(21) = [0,5]
trigger1 = var(18) != 1

[State -1, AI113];弱鳩
type = ChangeState
value = 1100
triggerall = alive = 1
triggerall = stateno = 240
triggerall = movehit = 2
triggerall = P2Life != 0
triggerall = IsHelper = 0
triggerall = var(20) = 1
triggerall = statetype != A
triggerall = p2statetype != A
triggerall = p2dist X = [50,100]
triggerall = p2movetype = H
trigger1 = var(18) = [3,4]
trigger1 = var(21) = [3,5]
trigger2 = var(18) = 2
trigger2 = var(21) = [3,4]

[State -1, AI114];強鳩
type = ChangeState
value = 1110
triggerall = alive = 1
triggerall = stateno = 240
triggerall = animtime = 0
;triggerall = movehit = 1
triggerall = P2Life != 0
triggerall = IsHelper = 0
triggerall = var(20) = 1
triggerall = statetype != A
triggerall = p2statetype = A
triggerall = p2dist X = [80,200]
triggerall = p2movetype = H
trigger1 = var(18) = [3,4]
trigger1 = var(21) = [3,5]
trigger2 = var(18) = 2
trigger2 = var(21) = [3,4]

[State -1, AI115];強ギフト
type = ChangeState
value = 1002
triggerall = alive = 1
triggerall = stateno = 240
triggerall = animtime = 0
;triggerall = movehit = 1
triggerall = P2Life != 0
triggerall = IsHelper = 0
triggerall = var(20) = 1
triggerall = p2statetype = A
triggerall = statetype != A
triggerall = p2dist X = [50,90]
triggerall = p2movetype = H
trigger1 = var(18) = [3,4]
trigger1 = var(21) = [0,2]
trigger2 = var(18) = 2
trigger2 = var(21) = 3


;-----------AIの行動 相手ダウン等時 -------

[State -1, AI116];近距離で相手ダウン(ギフト重ね)
type = ChangeState
value = 1000
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = ctrl
triggerall = NumHelper(1001) = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = statetype != A
triggerall = frontedgedist > 50
triggerall = p2stateno = [5100,5110]
triggerall = p2dist X = [30,145]
triggerall = p2movetype = H
trigger1 = var(18) = [3,4]
trigger1 = var(21) = [0,5]
trigger2 = var(18) = 2
trigger2 = var(21) = [0,3]
trigger3 = var(18) = 1
trigger3 = var(21) = [0,1]

[State -1, AI117];近距離で相手ダウン(ギフトある場合の攻撃続行)
type = ChangeState
value = 1200
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = ctrl
triggerall = NumHelper(1001) = 1
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = statetype != A
triggerall = p2stateno = [5100,5120]
triggerall = p2dist X = [30,125]
triggerall = p2movetype = H
trigger1 = var(18) = [3,4]
trigger1 = var(21) = [0,2]
trigger2 = var(18) = 2
trigger2 = var(21) = [0,1]
trigger3 = var(18) = 1
trigger3 = var(21) = 1
[State -1, AI118];近距離で相手ダウン(ギフトある場合の攻撃続行)
type = ChangeState
value = 82
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = ctrl
triggerall = NumHelper(1001) = 1
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = statetype != A
triggerall = p2stateno = [5100,5120]
triggerall = p2dist X = [30,125]
triggerall = p2movetype = H
trigger1 = var(18) = [3,4]
trigger1 = var(21) = [3,5]
trigger2 = var(18) = 2
trigger2 = var(21) = [3,4]
trigger3 = var(18) = 1
trigger3 = var(21) = 2

[State -1, AI119];至近距離で相手ダウン
type = ChangeState
value = 82
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = ctrl
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = statetype != A
triggerall = p2stateno = [5100,5110]
triggerall = p2dist X = [0,35]
triggerall = p2movetype = H
trigger1 = var(21) = 3

[State -1, AI120];至近距離で相手ダウン(バックジャンプ)
type = ChangeState
value = 84
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = ctrl
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = statetype != A
triggerall = p2stateno = [5100,5110]
triggerall = p2dist X = [0,35]
triggerall = p2movetype = H
trigger1 = var(21) = [0,2]
;;;;
[State -1, AI121];上のバックジャンプからラビット
type = ChangeState
value = 1150
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = ctrl
triggerall = P2Life != 0
triggerall = stateno = 85
triggerall = time = 15
triggerall = var(34) = 0
triggerall = var(20) = 1
triggerall = statetype = A
trigger1 = p2bodydist X = [20,140]
trigger1 = var(21) = [0,2]
;;;;
[State -1, AI122];上のバックジャンプから前方ジャンプ
type = ChangeState
value = 70
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = ctrl
triggerall = P2Life != 0
triggerall = stateno = 85
triggerall = time = 24
triggerall = var(34) = 0
triggerall = var(20) = 1
triggerall = statetype = A
trigger1 = p2bodydist X = [20,140]
trigger1 = var(21) = [3,5]

[State -1, AI123]
type = ChangeState
value = 1002
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = ctrl
triggerall = NumHelper(1001) = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = statetype != A
triggerall = p2stateno = [5050,5110]
triggerall = p2movetype = H
triggerall = FrontEdgeBodyDist >90
triggerall = p2dist X = [126,150]
trigger1 = var(21) = [0,4]
[State -1, AI124]
type = ChangeState
value = 1002
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = stateno = 2025
triggerall = NumHelper(1001) = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = statetype != A
triggerall = p2stateno = [5050,5120]
triggerall = p2movetype = H
;triggerall = FrontEdgeBodyDist >90
triggerall = p2dist X = [126,150]
trigger1 = 1
;
[State -1, AI125]
type = ChangeState
value = 100
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = ctrl
triggerall = NumHelper(1001) = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = statetype != A
triggerall = p2stateno = [5050,5110]
triggerall = p2movetype = H
triggerall = FrontEdgeBodyDist >90
triggerall = p2dist X = [150,190]
trigger1 = var(21) = [0,2]
[State -1, AI126]
type = ChangeState
value = 2025
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = ctrl
triggerall = NumHelper(1001) = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = statetype != A
triggerall = p2stateno = [5050,5110]
triggerall = p2movetype = H
triggerall = FrontEdgeBodyDist >90
triggerall = p2dist X = [150,190]
trigger1 = var(21) = [3,5]
[State -1, AI127]
type = ChangeState
value = 652
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = stateno = 102
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = statetype != A
triggerall = p2stateno = [5050,5110]
triggerall = p2movetype = H
triggerall = FrontEdgeBodyDist >90
trigger1 = p2dist X = [126,150]
trigger1 = var(21) = 5
trigger2 = p2dist X = [111,165]
trigger2 = p2dist X != [126,150]

[State -1, AI128];相手起き上がり時に密着
type = ChangeState
value = 80
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = ctrl
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = statetype != A
triggerall = p2stateno = 5120
triggerall = p2bodydist X = [0,4]
triggerall = p2movetype = I
trigger1 = var(21) = 0
trigger1 = var(18) != 1

[State -1, AI129];相手起き上がり時に密着
type = ChangeState
value = 1205
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = ctrl
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = statetype != A
triggerall = p2stateno = 5120
triggerall = p2bodydist X = [0,4]
;triggerall = p2movetype = I
trigger1 = var(21) = 1
trigger1 = var(18) != 1


;-----------AIの行動 攻撃被ガードされ後 -------

;立弱Ｐ　200
;↓
;立強Ｐへつなぐパターン
[State -1, AI130]
type = ChangeState
value = 200
triggerall = alive = 1
triggerall = stateno = 200
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = moveguarded = 2
triggerall = statetype != A
triggerall = p2dist X = [0,35]
triggerall = p2statetype != A
triggerall = p2movetype = H
trigger1 = var(21) = [0,2]
[State -1, AI131]
type = ChangeState
value = 210
triggerall = alive = 1
triggerall = stateno = 200
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = moveguarded = 2
triggerall = statetype != A
triggerall = p2dist X = [36,62]
triggerall = p2statetype != A
triggerall = p2movetype = H
trigger1 = var(21) = [0,5]
;
;空中ガードされた場合
[State -1, AI132]
type = ChangeState
value = 200
triggerall = alive = 1
triggerall = stateno = 200
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = moveguarded = 2
triggerall = statetype != A
triggerall = p2dist X = [0,35]
triggerall = p2statetype = A
triggerall = p2movetype = H
trigger1 = var(21) = [0,5]
[State -1, AI133]
type = ChangeState
value = 210
triggerall = alive = 1
triggerall = stateno = 200
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = moveguarded = 2
triggerall = statetype != A
triggerall = p2dist X = [36,62]
triggerall = p2statetype = A
triggerall = p2movetype = H
trigger1 = var(21) = [0,5]
;
;立強Ｋへつなぐパターン
[State -1, AI134]
type = ChangeState
value = 230
triggerall = alive = 1
triggerall = stateno = 200
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = moveguarded = 2
triggerall = statetype != A
triggerall = p2dist X = [0,40]
triggerall = p2statetype != A
triggerall = p2movetype = H
trigger1 = var(21) = [3,5]
[State -1, AI135]
type = ChangeState
value = 240
triggerall = alive = 1
triggerall = stateno = 230
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = moveguarded = var(21)
triggerall = statetype != A
triggerall = p2dist X = [36,77]
triggerall = p2statetype != A
triggerall = p2movetype = H
trigger1 = var(21) = [0,5]
;　　↓
;　　↓
;立強Ｐ立強Ｋからときどきステップやトリップに派生
;　　↓
[State -1, AI136]
type = ChangeState
value = 1200
triggerall = alive = 1
triggerall = stateno = 210
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = moveguarded = 2
triggerall = statetype != A
;triggerall = p2dist X = [0,40]
triggerall = p2statetype != A
triggerall = p2movetype = H
trigger1 = var(21) = 0
[State -1, AI137]
type = ChangeState
value = 105
triggerall = alive = 1
triggerall = stateno = 210
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = backedgebodydist > 60
triggerall = var(20) = 1
triggerall = moveguarded = 2
triggerall = statetype != A
;triggerall = p2dist X = [0,40]
triggerall = p2statetype != A
triggerall = p2movetype = H
trigger1 = var(21) = 3
[State -1, AI]138
type = ChangeState
value = 1200
triggerall = alive = 1
triggerall = stateno = 240
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = moveguarded = 1
triggerall = statetype != A
;triggerall = p2dist X = [0,40]
triggerall = p2statetype != A
triggerall = p2movetype = H
trigger1 = var(21) = 0
[State -1, AI139]
type = ChangeState
value = 105
triggerall = alive = 1
triggerall = stateno = 240
triggerall = IsHelper = 0
triggerall = backedgebodydist > 60
triggerall = var(20) = 1
triggerall = moveguarded = 4
triggerall = statetype != A
;triggerall = p2dist X = [0,40]
triggerall = p2statetype != A
triggerall = p2movetype = H
trigger1 = var(21) = 3

;屈弱Ｋ　430
;↓
;屈弱強Ｐへつなぐパターン
[State -1, AI140]
type = ChangeState
value = 400
triggerall = alive = 1
triggerall = stateno = 430
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = moveguarded = 2
triggerall = statetype != A
triggerall = p2dist X = [0,24]
triggerall = p2statetype != A
triggerall = p2movetype = H
trigger1 = var(21) = [0,2]
;↓
[State -1, AI141]
type = ChangeState
value = 410
triggerall = alive = 1
triggerall = stateno = 400
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = moveguarded = 2
triggerall = statetype != A
triggerall = p2dist X = [0,70]
triggerall = p2statetype != A
triggerall = p2movetype = H
trigger1 = var(21) = [0,2]
;
;屈弱強Ｋへつなぐパターン
[State -1, AI142]
type = ChangeState
value = 430
triggerall = alive = 1
triggerall = stateno = 430
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = moveguarded = 2
triggerall = statetype != A
triggerall = p2dist X = [0,24]
triggerall = p2statetype != A
triggerall = p2movetype = H
trigger1 = var(21) = [3,5]
;屈弱強Ｋへつなぐパターン
[State -1, AI143]
type = ChangeState
value = 400
triggerall = alive = 1
triggerall = stateno = 430
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = moveguarded = 4
triggerall = statetype != A
triggerall = p2dist X = [25,40]
triggerall = p2statetype != A
triggerall = p2movetype = H
trigger1 = var(21) = [0,5]
;↓
[State -1, AI144]
type = ChangeState
value = 440
triggerall = alive = 1
triggerall = stateno = 400
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = moveguarded = 7
triggerall = statetype != A
triggerall = p2dist X = [0,70]
triggerall = p2statetype != A
triggerall = p2movetype = H
trigger1 = var(21) = [0,5]
[State -1, AI145]
type = ChangeState
value = 440
triggerall = alive = 1
triggerall = stateno = 430
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = moveguarded = 7
triggerall = statetype != A
triggerall = p2dist X = [0,70]
triggerall = p2statetype != A
triggerall = p2movetype = H
trigger1 = var(21) = [0,5]
;
[State -1, AI146]
type = ChangeState
value = 410
triggerall = alive = 1
triggerall = stateno = 400
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = moveguarded = 2
triggerall = statetype != A
triggerall = p2dist X = [0,60]
triggerall = p2statetype = A
triggerall = p2movetype = H
trigger1 = 1
;
;立強Ｐ空中被ガード時は高確率で弱ピジョン
[State -1, AI147]
type = ChangeState
value = 1100
triggerall = alive = 1
triggerall = stateno = 210
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = moveguarded = 1
triggerall = statetype != A
triggerall = p2dist X = [0,40]
triggerall = p2statetype = A
triggerall = p2movetype = H
trigger1 = var(21) = [0,4]
;
;屈強Ｐ地上被ガード時はバックステップかトリップ
[State -1, AI148]
type = ChangeState
value = 105
triggerall = alive = 1
triggerall = stateno = 410
triggerall = IsHelper = 0
triggerall = var(20) = 1
triggerall = moveguarded = 2
triggerall = statetype != A
triggerall = p2dist X = [0,60]
triggerall = p2statetype != A
triggerall = p2movetype = H
trigger1 = var(21) = [0,2]
trigger1 = backedgedist > 40
[State -1, AI149]
type = ChangeState
value = 1205
triggerall = alive = 1
triggerall = stateno = 410
triggerall = IsHelper = 0
triggerall = var(20) = 1
triggerall = moveguarded = 2
triggerall = statetype != A
triggerall = p2dist X = [0,60]
triggerall = p2statetype != A
triggerall = p2movetype = H
trigger1 = var(21) = [3,4]
trigger2 = backedgedist <= 40
[State -1, AI150]
type = ChangeState
value = 1200
triggerall = alive = 1
triggerall = stateno = 410
triggerall = IsHelper = 0
triggerall = var(20) = 1
triggerall = moveguarded = 2
triggerall = statetype != A
triggerall = p2dist X = [0,60]
triggerall = p2statetype != A
triggerall = p2movetype = H
trigger1 = var(21) = 5

;-----------AIの行動 Ｊ攻撃ヒット後地上 -------

[State -1, AI151]
type = ChangeState
value = 210
triggerall = alive = 1
triggerall = stateno = 52
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = statetype != A
triggerall = p2stateno = [5000,5001]
triggerall = p2dist X = [-33,5]
triggerall = p2statetype != A
triggerall = p2movetype = H
trigger1 = var(18) = [3,4]
trigger1 = var(21) = [0,5]
trigger2 = var(18) = 2
trigger2 = var(21) = [0,3]
;　↓
[State -1, AI152];近距離
type = ChangeState
value = 1300
triggerall = alive = 1
triggerall =P2Life != 0
triggerall = var(20) = 1
triggerall = stateno = 210
triggerall = movehit
triggerall = p2statetype != A
triggerall = p2bodydist X <= 5
trigger1 = var(18) = [3,4]
trigger1 = var(21) = [0,5]
trigger2 = var(18) = 2
trigger2 = var(21) = [0,3]
trigger3 = var(18) = 1
trigger3 = var(21) = [0,1]

[State -1, AI153]
type = ChangeState
value = 200
triggerall = alive = 1
triggerall = stateno = 52
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = statetype != A
triggerall = p2stateno = [5000,5001]
triggerall = p2dist X = [-40,40]
triggerall = p2statetype != A
triggerall = p2movetype = H
trigger1 = var(21) = 5
;↓
[State -1, AI154];近距離
type = ChangeState
value = 650
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = stateno = 200
triggerall = movehit
triggerall = p2statetype != A
triggerall = p2bodydist X <= 2
trigger1 = var(18) = [3,4]
trigger1 = var(21) = [0,5]
trigger2 = var(18) = 2
trigger2 = var(21) = [0,3]
trigger3 = var(18) = 1
trigger3 = var(21) = [0,2]
[State -1, AI155];近距離
type = ChangeState
value = 230
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = stateno = 200
triggerall = movehit = 3
triggerall = p2statetype != A
triggerall = p2bodydist X <= 34
trigger1 = 1
;↓
[State -1, AI];近距離
type = ChangeState
value = 240
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall =P2Life != 0
triggerall = var(20) = 1
triggerall = stateno = 230
triggerall = movehit
triggerall = time > 7
triggerall = p2statetype != A
triggerall = p2bodydist X <= 65
trigger1 = 1

[State -1, AI]
type = ChangeState
value = 400
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = stateno = 52
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = statetype != A
triggerall = p2stateno = [5000,5001]
triggerall = p2dist X = [-40,40]
triggerall = p2statetype != A
triggerall = p2movetype = H
trigger1 = var(21) = [3,4]
[State -1, AI]
type = ChangeState
value = 430
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = stateno = 52
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = statetype != A
triggerall = p2stateno = [5000,5001]
triggerall = p2dist X = [-40,40]
triggerall = p2statetype != A
triggerall = p2movetype = H
trigger1 = var(21) = [0,2]
;　↓
[State -1, AI];近距離
type = ChangeState
value = 1300
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall =P2Life != 0
triggerall = var(20) = 1
triggerall = stateno = 430
triggerall = movehit
triggerall = time > 6
triggerall = p2statetype != A
triggerall = p2bodydist X <= 8
trigger1 = var(18) = [3,4]
trigger1 = var(21) = [0,2]
trigger2 = var(18) = 2
trigger2 = var(21) = [0,1]
[State -1, AI];近距離
type = ChangeState
value = 400
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall =P2Life != 0
triggerall = var(20) = 1
triggerall = stateno = 430
triggerall = movehit
triggerall = time > 6
triggerall = p2statetype != A
triggerall = p2bodydist X <= 8
trigger1 = var(21) = [3,5]
;　↓
[State -1, AI];近距離
type = ChangeState
value = 440
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall =P2Life != 0
triggerall = var(20) = 1
triggerall = stateno = 430
triggerall = movehit
triggerall = time > 6
triggerall = p2statetype != A
triggerall = p2bodydist X <= 31
trigger1 = var(18) = [3,4]
trigger1 = var(21) = [0,5]
trigger2 = var(18) = 2
trigger2 = var(21) = [0,4]
trigger3 = var(18) = 1
trigger3 = var(21) = [0,2]
[State -1, AI];近距離
type = ChangeState
value = 440
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall =P2Life != 0
triggerall = var(20) = 1
triggerall = stateno = 400
triggerall = movehit
triggerall = time > 6
triggerall = p2statetype != A
triggerall = p2bodydist X <= 31
trigger1 = var(18) = [3,4]
trigger1 = var(21) = [0,5]
trigger1 = var(21) = [0,5]
trigger2 = var(18) = 2
trigger2 = var(21) = [0,4]
trigger3 = var(18) = 1
trigger3 = var(21) = [0,3]

;-----------AIの行動 ステップ派生行動 -------
;stateからの派生行動
[State -1, AI];スライディング
type = ChangeState
value = 650
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = stateno = 102
triggerall = statetype != A
triggerall = p2statetype != A
triggerall = p2bodydist X = [30,90]
trigger1 = var(18) = [3,4]
trigger1 = var(21) = [3,4]
trigger2 = var(18) = [1,2]
trigger2 = var(21) = [3,4]

[State -1, AI];スライディング
type = ChangeState
value = 650
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = stateno = 102
triggerall = statetype != A
triggerall = p2statetype = S
triggerall = p2bodydist X = [30,90]
trigger1 = var(18) = [3,4]
trigger1 = var(21) = [3,5]
trigger2 = var(18) = [1,2]
trigger2 = var(21) = 3

;-----------AIの行動 歩行中の動作 -------
;state25からの派生行動

[State -1, AI];テスト用
type = null;ChangeState
value = 2025
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = command = "start"
triggerall = P2Life != 0
triggerall = ctrl
trigger1 = statetype != A

[State -1, AI]
type = ChangeState
value = 1000
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = NumHelper(1001) = 0
triggerall = var(20) = 1
triggerall = stateno = 2025
triggerall = statetype != A
triggerall = p2statetype = L
triggerall = p2bodydist X = [15,40]
triggerall = p2stateno = [5100,5110]
triggerall = p2movetype = H
trigger1 = var(18) = [3,4]
trigger1 = var(21) = [0,5]
trigger2 = var(18) = 2
trigger2 = var(21) = [0,4]
[State -1, AI]
type = ChangeState
value = 82
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = NumHelper(1001) = 1
triggerall = var(20) = 1
triggerall = stateno = 2025
triggerall = statetype != A
triggerall = p2statetype = L
triggerall = p2bodydist X = [15,40]
triggerall = p2stateno = [5100,5110]
triggerall = p2movetype = H
trigger1 = var(18) = [3,4]
trigger1 = var(21) = [0,5]
trigger2 = var(18) = 2
trigger2 = var(21) = [0,3]
trigger3 = var(18) = 1
trigger3 = var(21) = [0,1]

[State -1, AI]
type = ChangeState
value = 240
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = stateno = 2025
triggerall = statetype != A
triggerall = p2statetype != L
triggerall = p2bodydist X = [14,34]
trigger1 = var(21) = 0

[State -1, AI]
type = ChangeState
value = 200
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = stateno = 2025
triggerall = statetype != A
triggerall = p2statetype != L
triggerall = p2bodydist X = [0,15]
trigger1 = var(21) = 0
trigger2 = var(21) = 1

[State -1, AI];投げる
type = ChangeState
value = 800
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = stateno = 2025
triggerall = statetype != A
triggerall = p2statetype != A
triggerall = p2movetype != H 
triggerall = p2bodydist X = [0,3]
trigger1 = var(18) = [2,4]
trigger1 = var(21) = [2,3]
[State -1, AI];効率的でない行動
type = ChangeState
value = 210
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = stateno = 2025
triggerall = statetype != A
triggerall = p2statetype != A
triggerall = p2movetype != H 
triggerall = p2bodydist X = [0,3]
trigger1 = var(18) = 1
trigger1 = var(21) = [2,3]

;
[State -1, AI];しゃがみ弱K
type = ChangeState
value = 430
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = stateno = 2025
triggerall = statetype != A
triggerall = p2statetype != A
triggerall = p2bodydist X = [0,15]
trigger1 = var(21) = [2,3]
;
[State -1, AI]
type = ChangeState
value = 410
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = stateno = 2025
triggerall = statetype != A
triggerall = p2statetype = A
triggerall = p2bodydist X = [0,18]
trigger1 = var(21) = [2,3]

[State -1, AI];しゃがみ弱P
type = ChangeState
value = 430
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = stateno = 2025
triggerall = statetype != A
triggerall = p2statetype != A
triggerall = p2bodydist X = [0,15]
trigger1 = var(21) = 4

[State -1, AI]
type = ChangeState
value = 650
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = stateno = 2025
triggerall = statetype != A
triggerall = p2statetype = S
triggerall = p2bodydist X = [0,20]
trigger1 = var(21) = [4,5]

[State -1, AI]
type = ChangeState
value = 230
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = stateno = 2025
triggerall = statetype != A
triggerall = p2statetype != A 
triggerall = p2bodydist X = [0,20]
trigger1 = var(21) = 5

[State -1, AI]
type = ChangeState
value = 1300
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = stateno = 2025
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = statetype != A
triggerall = p2statetype != A
triggerall = p2movetype = A
triggerall = enemy,time < 4
triggerall = p2bodydist X = [0,68]
trigger1 = var(18) = 4
trigger1 = var(21) = [0,4]
trigger2 = var(18) = 3
trigger2 = var(21) = [0,3]
trigger3 = var(18) = 2
trigger3 = var(21) = [0,2]
trigger4 = var(18) = 1
trigger4 = var(21) = 0

[State -1, AI]
type = ChangeState
value = 80
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = stateno = 2025
triggerall = p2bodydist X = [-4,0]
trigger1 = var(18) = 4
trigger1 = var(21) = [0,5]
trigger2 = var(18) = 3
trigger2 = var(21) = [0,5]
trigger3 = var(18) = 2
trigger3 = var(21) = [0,4]
trigger4 = var(18) = 1
trigger4 = var(21) = 0


;-----------AIの行動 ラビットカード -------
[State -1, rabit1];
type = ChangeState
value = 1150
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = var(34) = 0
triggerall = statetype = A
triggerall = p2statetype != A
triggerall = pos Y = [-30,-10]
triggerall = ctrl
triggerall = p2bodydist X = [-40,-10]
trigger1 = var(18) = [3,4]
trigger1 = var(21) = [0,2]
trigger2 = var(18) = 2
trigger2 = var(21) = [0,1]
trigger3 = var(18) = 1
trigger3 = var(21) = 0

[State -1, rabit2];
type = ChangeState
value = 1150
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = var(34) = 0
triggerall = statetype = A
triggerall = p2statetype != A
triggerall = pos Y = [-30,-10]
triggerall = ctrl
triggerall = p2bodydist X = [8,45]
trigger1 = var(18) = [3,4]
trigger1 = var(21) = [4,5]
trigger2 = var(18) = 2
trigger2 = var(21) = [4,5]
trigger3 = var(18) = 1
trigger3 = var(21) = 4

[State -1, rabit3];
type = ChangeState
value = 1150
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = var(34) = 0
triggerall = statetype = A
triggerall = p2statetype != A
triggerall = pos Y = [-30,-10]
triggerall = ctrl
triggerall = p2bodydist X = [40,90]
trigger1 = var(18) = [3,4]
trigger1 = var(21) = [3,5]
trigger2 = var(18) = 2
trigger2 = var(21) = [3,4]
trigger3 = var(18) = 1
trigger3 = var(21) = 3

[State -1, rabit4];
type = ChangeState
value = 1150
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = var(34) = 0
triggerall = statetype = A
triggerall = p2statetype != A
triggerall = pos Y = [-40,-20]
triggerall = ctrl
triggerall = p2bodydist X = [80,130]
trigger1 = var(21) = 0
trigger2 = var(21) = 1

[State -1, rabit5];
type = ChangeState
value = 1160
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = var(34) = 0
triggerall = statetype = A
triggerall = p2statetype != A
triggerall = pos Y = [-40,-20]
triggerall = ctrl
triggerall = p2bodydist X = [80,130]
trigger1 = var(21) = 2

[State -1, rabit6];
type = ChangeState
value = 1160
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = var(34) = 0
triggerall = statetype = A
;triggerall = p2statetype != A
triggerall = pos Y = [-50,-20]
triggerall = ctrl
triggerall = p2bodydist X >= 140
trigger1 = var(18) = [2,4]
trigger1 = var(21) = [0,2]
trigger2 = var(18) = 1
trigger2 = var(21) = [0,1]

[State -1, rabit7];
type = ChangeState
value = 1150
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = var(34) = 0
triggerall = statetype = A
;triggerall = p2statetype != A
triggerall = pos Y = [-50,-20]
triggerall = ctrl
triggerall = p2bodydist X >= 140
trigger1 = var(18) = [2,4]
trigger1 = var(21) = [3,4]
trigger2 = var(18) = 1
trigger2 = var(21) = 3

[State -1, rabit8];
type = ChangeState
value = 1160
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = var(34) = 0
triggerall = statetype = A
triggerall = p2statetype != A
triggerall = vel X <= -1
triggerall = pos Y = [-80,-20]
triggerall = ctrl
triggerall = p2bodydist X = [80,130]
trigger1 = var(18) = [2,4]
trigger1 = var(21) = [3,5]
trigger2 = var(18) = 1
trigger2 = var(21) = 5

;-----------AIの行動 密着A ------------------
;密着で相手が地上にいる時の行動パターン

;密着間合いで投げを狙います
[State -1, AI];近距離
type = ChangeState
value = 800
triggerall = var(18) = [3,4]
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = statetype != A
triggerall = ctrl
triggerall = p2statetype != A
triggerall = p2statetype != L
triggerall = p2movetype != H 
triggerall = p2bodydist X = [0,2]
trigger1 = var(21) = 0
trigger2 = var(21) = 3
[State -1, AI];近距離
type = ChangeState
value = 800
triggerall = var(18) = [1,2]
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = statetype != A
triggerall = ctrl
triggerall = p2statetype != A
triggerall = p2statetype != L
triggerall = p2movetype != H 
triggerall = p2bodydist X = [0,2]
trigger1 = var(21) = 0

;立弱キック
[State -1, AI];近距離
type = ChangeState
value = 230
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = statetype != A
triggerall = ctrl
triggerall = p2statetype != A
triggerall = p2statetype != L
triggerall = p2bodydist X <= 7
trigger1 = var(21) = 0

;しゃがみ弱キック
[State -1, AI];近距離
type = ChangeState
value = 430
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = statetype != A
triggerall = ctrl
triggerall = p2statetype != A
triggerall = p2statetype != L
triggerall = p2bodydist X <= 7
trigger1 = var(21) = [1,2]

;立ち弱キック
[State -1, AI];近距離
type = ChangeState
value = 230
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = statetype != A
triggerall = ctrl
triggerall = p2statetype != A
triggerall = p2statetype != L
triggerall = p2bodydist X <= 7
trigger1 = var(21) = 3

;しゃがみ弱パンチ
[State -1, AI];近距離
type = ChangeState
value = 400
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = statetype != A
triggerall = ctrl
triggerall = p2statetype != A
triggerall = p2statetype != L
triggerall = p2bodydist X <= 7
trigger1 = var(21) = 4

;立弱P
[State -1, AI];近距離
type = ChangeState
value = 200
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = statetype != A
triggerall = ctrl
triggerall = p2statetype != A
triggerall = p2statetype != L
triggerall = p2bodydist X <= 7
trigger1 = var(21) = 5

;-----------AIの行動 至近距離 ------------------
;密着間合いより少し離れた至近距離での行動です

;立弱キック
[State -1, AI];近距離
type = ChangeState
value = 230
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = statetype != A
triggerall = ctrl
triggerall = p2statetype != A
triggerall = p2bodydist X = [8,23]
trigger1 = var(21) = 0

;しゃがみ弱キック
[State -1, AI];近距離
type = ChangeState
value = 430
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = statetype != A
triggerall = ctrl
triggerall = p2statetype != A
triggerall = p2bodydist X = [8,23]
trigger1 = var(21) = 1

;しゃがみ弱キック
[State -1, AI];近距離
type = ChangeState
value = 430
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = statetype != A
triggerall = ctrl
triggerall = p2statetype != A
triggerall = p2bodydist X = [8,23]
trigger1 = var(21) = 2

;立ち強キック
[State -1, AI];近距離
type = ChangeState
value = 210
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = statetype != A
triggerall = ctrl
triggerall = p2statetype != A
triggerall = p2bodydist X = [8,23]
trigger1 = var(21) = 3

;立ち弱パンチ
[State -1, AI];近距離
type = ChangeState
value = 200
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = statetype != A
triggerall = ctrl
triggerall = p2statetype != A
triggerall = p2bodydist X = [8,23]
trigger1 = var(21) = 4

[State -1, AI];近距離
type = ChangeState
value = 400
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = statetype != A
triggerall = ctrl
triggerall = p2statetype != A
triggerall = p2bodydist X = [8,12]
trigger1 = var(21) = 5
[State -1, AI];近距離
type = ChangeState
value = 80
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = statetype != A
triggerall = ctrl
triggerall = p2statetype != A
triggerall = p2bodydist X = [13,23]
trigger1 = var(18) != 1
trigger1 = var(21) = 5
;↓
[State -1, AI];近距離
type = ChangeState
value = 1500
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = time < 10
triggerall = var(20) = 1
triggerall = stateno = 50
;triggerall = anim = 41
triggerall = ctrl
triggerall = p2statetype != A
triggerall = p2bodydist X = [-8,43]
triggerall = p2dist Y = [28,35]
trigger1 = 1
[State -1, AI];近距離
type = ChangeState
value = 1500
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = time < 10
triggerall = var(20) = 1
triggerall = stateno = 81
;triggerall = anim = 41
triggerall = ctrl
triggerall = p2statetype != A
triggerall = p2bodydist X = [-8,43]
triggerall = p2dist Y = [28,35]
trigger1 = 1


;-----------AIの行動 牽制間合い ------------------
;牽制間合い

;
[State -1, AI];牽制間合い
type = ChangeState
value = 230
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall =P2Life != 0
triggerall = var(20) = 1
triggerall = statetype != A
triggerall = ctrl
triggerall = p2statetype != A
triggerall = p2bodydist X = [23,31]
trigger1 = var(21) = 0

;
[State -1, AI];牽制間合い
type = ChangeState
value = 2025
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall =P2Life != 0
triggerall = var(20) = 1
triggerall = statetype != A
triggerall = ctrl
triggerall = p2statetype != A
triggerall = p2bodydist X = [23,31]
trigger1 = var(21) = 1

;
[State -1, AI];牽制間合い
type = ChangeState
value = 240
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall =P2Life != 0
triggerall = var(20) = 1
triggerall = statetype != A
triggerall = ctrl
triggerall = p2statetype != A
triggerall = p2bodydist X = [23,31]
trigger1 = var(21) = [2,3]

;立ち弱パンチ
[State -1, AI];牽制間合い
type = ChangeState
value = 200
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = statetype != A
triggerall = ctrl
triggerall = p2statetype != A
triggerall = p2bodydist X = [23,31]
trigger1 = var(21) = 4

;ジャンプ
[State -1, AI];牽制間合い
type = ChangeState
value = 82
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = statetype != A
triggerall = ctrl
triggerall = p2statetype != A
triggerall = p2bodydist X = [23,27]
trigger1 = var(21) = 5

;スライディング
[State -1, AI];牽制間合い
type = ChangeState
value = 650
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = statetype != A
triggerall = ctrl
triggerall = p2statetype != A
triggerall = p2bodydist X = [27,31]
trigger1 = var(21) = 5


;-----------AIの行動 中距離 ------------------
;中距離

;立強キック
[State -1, AI];中距離
type = ChangeState
value = 230
triggerall = var(18) = [2,4]
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = statetype != A
triggerall = ctrl
triggerall = p2statetype != A
triggerall = p2bodydist X = [32,51]
trigger1 = var(21) = 0

;
[State -1, AI]
type = ChangeState
value = 1205
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = var(32) = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = statetype != A
triggerall = ctrl
triggerall = p2statetype != A
triggerall = p2bodydist X = [32,46]
trigger1 = var(21) = 1
;強ピジョン
[State -1, AI]
type = ChangeState
value = 1100
triggerall = var(18) = 1
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = var(32) = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = statetype != A
triggerall = ctrl
triggerall = p2statetype != A
triggerall = p2bodydist X = [47,51]
trigger1 = var(21) = 1
;弱ピジョン
[State -1, AI]
type = ChangeState
value = 1100
triggerall = var(18) = [2,4]
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = var(32) = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = statetype != A
triggerall = ctrl
triggerall = p2statetype != A
triggerall = p2bodydist X = [47,51]
trigger1 = var(21) = 1

;前進
[State -1, AI]
type = ChangeState
value = 2025
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = statetype != A
triggerall = ctrl
triggerall = p2statetype != A
triggerall = p2bodydist X = [32,51]
trigger1 = var(21) = 2

;弱ギフト
[State -1, AI]
type = ChangeState
value = 1000
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = NumHelper(1001) = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = statetype != A
triggerall = ctrl
triggerall = p2statetype != A
triggerall = p2bodydist X = [32,51]
trigger1 = var(21) = 3
;
;ギフトでているとき
;弱トリップ
[State -1, AI]
type = ChangeState
value = 1200
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = NumHelper(1001) = 1
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = statetype != A
triggerall = ctrl
triggerall = p2statetype != A
triggerall = p2bodydist X = [32,51]
trigger1 = var(21) = 3

;強Ｋ
[State -1, AI]
type = ChangeState
value = 240
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall =P2Life != 0
triggerall = var(20) = 1
triggerall = statetype != A
triggerall = ctrl
triggerall = p2statetype != A
triggerall = p2bodydist X = [32,51]
trigger1 = var(21) = 4

;強トリップ
[State -1, AI]
type = ChangeState
value = 1205
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = statetype != A
triggerall = ctrl
triggerall = p2statetype != A
triggerall = p2bodydist X = [32,51]
trigger1 = var(21) = 5

;-----------AIの行動 中距離 ------------------
;中距離

[State -1, AI];距離確認
type = null;Palfx
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = p2bodydist X = [52,82]
trigger1 = 1
time = 1
add = -60,80,-30

;ジャンプ
[State -1, AI];中距離
type = ChangeState
value = 82
triggerall = var(18) != 1
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = statetype != A
triggerall = ctrl
;triggerall = p2statetype != A
triggerall = p2bodydist X = [52,82]
trigger1 = var(21) = 0
trigger2 = var(21) = 4
;ロングジャンプ
[State -1, AI];中距離
type = ChangeState
value = 115
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = statetype != A
triggerall = ctrl
;triggerall = p2statetype != A
triggerall = p2bodydist X = [83,98]
trigger1 = var(21) = 0
trigger2 = var(21) = 4

[State -1, AI];中距離
type = ChangeState
value = 2025
triggerall = var(18) = 1
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = statetype != A
triggerall = ctrl
;triggerall = p2statetype != A
triggerall = p2bodydist X = [52,82]
trigger1 = var(21) = 0
trigger2 = var(21) = 4

[State -1, AI];中距離
type = ChangeState
value = 650
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = ctrl
triggerall = statetype != A
triggerall = p2statetype = S
triggerall = p2bodydist X = [52,72]
trigger1 = var(21) = 1

;ステップ
[State -1, AI];中距離
type = ChangeState
value = 100
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = statetype != A
triggerall = ctrl
triggerall = p2bodydist X = [73,98]
trigger1 = var(21) = 1
[State -1, AI];中距離スライディング
type = ChangeState
value = 652
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = stateno = 102
triggerall = statetype != A
triggerall = p2statetype = S
triggerall = p2bodydist X = [-2,34]
trigger1 = 1;var(21) = 1
[State -1, AI];遠距離スライディング
type = ChangeState
value = 652
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = stateno = 102
triggerall = statetype != A
triggerall = p2statetype = S
triggerall = p2bodydist X = [75,110]
trigger1 = var(21) = [0,3]


;後退
[State -1, AI]
type = ChangeState
value = 2026
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = var(32) = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = statetype != A
triggerall = NumHelper(1001) = 0
triggerall = p2movetype != H
triggerall = var(32) = 0
triggerall = ctrl
;triggerall = p2statetype != A
triggerall = p2bodydist X = [52,98]
trigger1 = var(21) = 2
;
[State -1, AI];ギフトがでているときは強気にハイジャンプ
type = ChangeState
value = 115
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = var(32) = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = statetype != A
triggerall = NumHelper(1001) = 1
triggerall = var(32) = 0
triggerall = ctrl
;triggerall = p2statetype != A
triggerall = p2bodydist X = [52,98]
trigger1 = var(21) = 2

[State -1, AI];バックステップ
type = ChangeState
value = 105
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = statetype != A
triggerall = p2movetype != H
triggerall = ctrl
;triggerall = p2statetype != A
triggerall = p2bodydist X = [52,98]
trigger1 = var(21) = 3
[State -1, AI];バックステップ＞ルミナステップ
type = ChangeState
value = 1450
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = statetype != A
triggerall = stateno = 107
triggerall = time > 2
triggerall = p2statetype != A
triggerall = p2bodydist X = [140,178]
trigger1 = var(21) = 3
trigger2 = var(21) = 4
trigger3 = var(21) = 5
[State -1, AI];バックステップ＞強ルミナステップ
type = ChangeState
value = 1450
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = statetype != A
triggerall = stateno = 107
triggerall = time > 2
triggerall = p2statetype != A
triggerall = p2bodydist X = [185,224]
trigger1 = var(21) = 3
trigger2 = var(21) = 4
trigger3 = var(21) = 5

[State -1, AI];ハイジャンプ@
type = ChangeState
value = 115
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = statetype != A
triggerall = p2movetype = H
triggerall = ctrl
;triggerall = p2statetype != A
triggerall = p2bodydist X = [52,98]
trigger1 = var(21) = 3

;弱ピジョン
[State -1, AI]
type = ChangeState
value = 1100
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = var(32) = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = statetype != A
triggerall = ctrl
triggerall = p2statetype != A
triggerall = p2bodydist X = [52,98]
trigger1 = var(21) = 5
;弱ギフト
[State -1, AI]
type = ChangeState
value = 1002
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = NumHelper(1001) = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = statetype != A
triggerall = ctrl
triggerall = p2statetype != A
triggerall = p2bodydist X = [52,98]
trigger1 = var(21) = 5

;-----------AIの行動 中遠距離 ------------------
;中遠距離
[State -1, AI];距離確認
type = null;Palfx
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = p2bodydist X = [99,145]
trigger1 = 1
time = 1
add = 60,0,-30

;
[State -1, AI];中距離スライディング
type = ChangeState
value = 650
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = statetype != A
triggerall = ctrl
triggerall = p2statetype != A
triggerall = p2bodydist X = [99,145]
trigger1 = var(21) = 0

;ピジョン
[State -1, AI]
type = ChangeState
value = 1100
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = var(32) = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = statetype != A
triggerall = ctrl
;triggerall = p2statetype != A
trigger1 = p2bodydist X = [99,115]
trigger1 = 1;var(21) = 1
trigger2 = p2bodydist X = [115,145]
trigger2 = enemy,vel X > 1
trigger2 = var(21) = 1
[State -1, AI]
type = ChangeState
value = 1110
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = var(32) = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = statetype != A
triggerall = ctrl
;triggerall = p2statetype != A
triggerall = p2bodydist X = [115,145]
trigger2 = enemy,vel X <= 1
trigger1 = var(21) = 1
;強ピジョン出せない時
[State -1, AI]
type = ChangeState
value = 1205
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = var(32) = 1
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = statetype != A
triggerall = ctrl
;triggerall = p2statetype != A
triggerall = p2bodydist X = [99,145]
trigger1 = var(21) = 1

;前ステップ
[State -1, AI]
type = ChangeState
value = 100
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = statetype != A
triggerall = ctrl
;triggerall = p2statetype != A
triggerall = p2bodydist X = [99,145]
trigger1 = var(21) = 2

;強ギフト
[State -1, AI]
type = ChangeState
value = 1002
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = NumHelper(1001) = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = statetype != A
triggerall = ctrl
;triggerall = p2statetype != A
triggerall = p2bodydist X = [99,145]
trigger1 = var(21) = 3
;強ギフト出せない時
[State -1, AI]
type = ChangeState
value = 115
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = NumHelper(1001) = 1
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = statetype != A
triggerall = ctrl
;triggerall = p2statetype != A
triggerall = p2bodydist X = [99,145]
trigger1 = var(21) = 3

;
[State -1, AI]
type = ChangeState
value = 1200
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall =P2Life != 0
triggerall = var(20) = 1
triggerall = statetype != A
triggerall = ctrl
;triggerall = p2statetype != A
triggerall = p2bodydist X = [99,145]
trigger1 = var(21) = 4

;
[State -1, AI]
type = ChangeState
value = 1400
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall =P2Life != 0
triggerall = var(20) = 1
triggerall = statetype != A
triggerall = ctrl
;triggerall = p2statetype != A
triggerall = p2bodydist X = [99,145]
trigger1 = var(21) = 5


;-----------AIの行動 遠距離 ------------------
;遠距離
[State -1, AI];距離確認
type = null;Palfx
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = p2bodydist X = [146,275]
trigger1 = 1
time = 1
add = -30,-30,60

;ハイジャンプ
[State -1, AI];遠距離
type = ChangeState
value = 115
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall =P2Life != 0
triggerall = var(20) = 1
triggerall = statetype != A
triggerall = ctrl
triggerall = p2bodydist X = [146,275]
trigger1 = var(21) = 0

;強ピジョン
[State -1, AI]
type = ChangeState
value = 1110
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = var(32) = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = statetype != A
triggerall = ctrl
triggerall = p2bodydist X = [146,275]
trigger1 = var(21) = 1
;強ピジョン出せない時
[State -1, AI]
type = ChangeState
value = 1205
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = var(32) = 1
triggerall = P2Life != 0
triggerall = statetype != A
triggerall = var(20) = 1
triggerall = ctrl
triggerall = p2bodydist X = [153,188]
trigger1 = var(21) = [1,3]
[State -1, AI]
type = ChangeState
value = 1205
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = var(32) = 1
triggerall = P2Life != 0
triggerall = statetype != A
triggerall = var(20) = 1
triggerall = ctrl
triggerall = p2bodydist X = [146,275]
trigger1 = var(21) = 1

;
[State -1, AI]
type = ChangeState
value = 1200
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = statetype != A
triggerall = ctrl
triggerall = p2bodydist X = [146,235]
trigger1 = var(21) = 2
[State -1, AI]
type = ChangeState
value = 1205
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = statetype != A
triggerall = ctrl
;triggerall = p2statetype != A
triggerall = p2bodydist X = [146,275]
trigger1 = var(21) = 2

;ギフト
[State -1, AI]
type = ChangeState
value = 1002
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = NumHelper(1001) = 0
triggerall = P2Life != 0
triggerall = var(20) = 1
triggerall = statetype != A
triggerall = ctrl
;triggerall = p2statetype != A
triggerall = p2bodydist X = [146,155]
trigger1 = var(21) = 3
;ギフト出せない時
[State -1, AI]
type = ChangeState
value = 115
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall = NumHelper(1001) = 1
triggerall = P2Life != 0
triggerall = var(20) = 1
;triggerall = statetype != A
triggerall = ctrl
triggerall = p2bodydist X = [156,275]
trigger1 = var(21) = 3
trigger1 = var(18) != 1

;
[State -1, AI]
type = ChangeState
value = 2025
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall =P2Life != 0
triggerall = var(20) = 1
triggerall = statetype != A
triggerall = ctrl
;triggerall = p2statetype != A
triggerall = p2bodydist X = [146,275]
trigger1 = var(21) = 4

;
[State -1, AI]
type = ChangeState
value = 115
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall =P2Life != 0
triggerall = var(20) = 1
triggerall = statetype != A
triggerall = ctrl
;triggerall = p2statetype != A
triggerall = p2bodydist X = [146,153]
trigger1 = var(21) = 5
[State -1, AI]
type = ChangeState
value = 1450
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall =P2Life != 0
triggerall = var(20) = 1
triggerall = statetype != A
triggerall = ctrl
;triggerall = p2statetype != A
triggerall = p2bodydist X = [153,180]
trigger1 = var(21) = 5
[State -1, AI]
type = ChangeState
value = 115
triggerall = alive = 1
triggerall = IsHelper = 0
triggerall =P2Life != 0
triggerall = var(20) = 1
triggerall = statetype != A
triggerall = ctrl
;triggerall = p2statetype != A
triggerall = p2bodydist X = [180,275]
trigger1 = var(21) = 5



;===========================================================================

[State -1, Smash Kung Fu Upper]
type = ChangeState
value = 60
trigger1 = stateno = 1210
trigger1 = time > 7
trigger1 = var(26) = 0
trigger1 = command = "holdup"
trigger1 = Pos Y <= -20
trigger2 = stateno = 116
trigger2 = time > 21
trigger2 = var(26) = 0
trigger2 = command = "holdup"
trigger2 = Pos Y <= -20

;---------------------------------------------------------------------------
[State -1, Triple Kung Fu Palm]
type = ChangeState
value = 3000
triggerall = command = "Super1"
triggerall = power >= 1000
trigger1 = statetype = S
trigger1 = ctrl
trigger2 = var(20) = 0
trigger2 = statetype != A
trigger2 = hitdefattr = SC, NA, SA, HA
trigger2 = stateno != [3000,3050)
trigger2 = movecontact

[State -1, Triple Kung Fu Palm]
type = ChangeState
value = 3005
triggerall = command = "Super2"
triggerall = power >= 1000
trigger1 = statetype = S
trigger1 = ctrl
trigger2 = var(20) = 0
trigger2 = statetype != A
trigger2 = hitdefattr = SC, NA, SA, HA
trigger2 = stateno != [3000,3050)
trigger2 = movecontact

[State -1, Triple Kung Fu Palm]
type = null;ChangeState
value = 3100
triggerall = command = "Super3"
triggerall = power >= 2000
trigger1 = statetype = S
trigger1 = ctrl
trigger2 = var(20) = 0
trigger2 = statetype != A
trigger2 = hitdefattr = SC, NA, SA, HA
trigger2 = stateno != [3000,3050)
trigger2 = movecontact


;===========================================================================
[State -1, Kung Fu Throw]
type = ChangeState
value = 800
triggerall = command = "xa"
triggerall = statetype != A
triggerall = ctrl
trigger1 = stateno != 100
trigger1 = p2bodydist X < 8

;===========================================================================
;This is not a move, but it sets up var(1) to be 1 if conditions are right
;for a combo into a special move (used below).
;Since a lot of special moves rely on the same conditions, this reduces
;redundant logic.
[State -1, Combo condition Reset]
type = VarSet
trigger1 = 1
var(1) = 0

[State -1, Combo condition Check]
type = VarSet
trigger1 = statetype != A
trigger1 = ctrl
trigger2 = (stateno = [200,299]) || (stateno = [400,499])
trigger2 = stateno != 440 ;Except for sweep kick
trigger2 = movecontact
var(1) = 1

;---------------------------------------------------------------------------
;luminouStep
[State -1, Light Kung Fu Blow]
type = ChangeState
value = 1400
triggerall = command = "step"
triggerall = statetype != A
trigger1 = ctrl
trigger2 = var(1) ;Use combo condition (above)

[State -1,  Light Kung Fu Blow];先行入力
type = VarSet
v = 29
triggerall = command = "step"
trigger1 = movetype = I
trigger1 = stateno = 101
trigger2 = movetype = I
trigger2 = stateno = 102
trigger3 = movetype = I
trigger3 = stateno = 106
trigger4 = movetype = I
trigger4 = stateno = 107
trigger5 = movetype = H
trigger5 = stateno = 5120
trigger5 = time > 6
value = 1400

[State -1,  Light Kung Fu Blow];先行入力
type = ChangeState
triggerall = var(29) = 1400
trigger1 = stateno = 102
trigger1 = movetype = I
trigger1 = time > 2
trigger2 = stateno = 107
trigger2 = movetype = I
trigger2 = time > 2
trigger3 = stateno = 5120
trigger3 = movetype = H
trigger3 = animtime = 0
value = 1400

[State -1, Light Kung Fu Blow]
type = ChangeState
value = 1450
triggerall = command = "step2"
triggerall = statetype != A
trigger1 = ctrl
trigger2 = var(1) ;Use combo condition (above)

[State -1,  Light Kung Fu Blow];先行入力
type = VarSet
v = 29
triggerall = command = "step2"
trigger1 = movetype = I
trigger1 = stateno = 101
trigger2 = movetype = I
trigger2 = stateno = 102
trigger3 = movetype = I
trigger3 = stateno = 106
trigger4 = movetype = I
trigger4 = stateno = 107
trigger5 = movetype = H
trigger5 = stateno = 5120
trigger5 = time > 6
value = 1450

[State -1,  Light Kung Fu Blow];先行入力
type = ChangeState
triggerall = var(29) = 1450
trigger1 = stateno = 102
trigger1 = movetype = I
trigger1 = time > 2
trigger2 = stateno = 107
trigger2 = movetype = I
trigger2 = time > 2
trigger3 = stateno = 5120
trigger3 = movetype = H
trigger3 = animtime = 0
value = 1450

;---------------------------------------------------------------------------
;Star Stairs
[State -1, Light Kung Fu Blow]
type = ChangeState
value = 1300
triggerall = command = "upper_x"
triggerall = statetype != A
trigger1 = ctrl
trigger2 = var(1) ;Use combo condition (above)

[State -1, Light Kung Fu Blow]
type = ChangeState
value = 1300
triggerall = command = "upper_y"
triggerall = statetype != A
trigger1 = ctrl
trigger2 = var(1)

[State -1,  Light Kung Fu Blow];先行入力
type = VarSet
v = 29
triggerall = command = "upper_x"
trigger1 = movetype = I
trigger1 = stateno = 101
trigger2 = movetype = I
trigger2 = stateno = 102
trigger3 = movetype = I
trigger3 = stateno = 106
trigger4 = movetype = I
trigger4 = stateno = 107
trigger5 = movetype = H
trigger5 = stateno = 5120
trigger5 = time > 6
value = 1300

[State -1,  Light Kung Fu Blow];先行入力
type = VarSet
v = 29
triggerall = command = "upper_y"
trigger1 = movetype = I
trigger1 = stateno = 101
trigger2 = movetype = I
trigger2 = stateno = 102
trigger3 = movetype = I
trigger3 = stateno = 106
trigger4 = movetype = I
trigger4 = stateno = 107
trigger5 = movetype = H
trigger5 = stateno = 5120
trigger5 = time > 6
value = 1300

[State -1,  Light Kung Fu Blow];先行入力
type = ChangeState
triggerall = var(29) = 1300
trigger1 = stateno = 102
trigger1 = movetype = I
trigger1 = time > 2
trigger2 = stateno = 107
trigger2 = movetype = I
trigger2 = time > 2
trigger3 = stateno = 5120
trigger3 = movetype = H
trigger3 = animtime = 0
value = 1300

;---------------------------------------------------------------------------
[State -1, Light Kung Fu Palm]
type = ChangeState
value = 1100
triggerall = command = "QCF_x"
triggerall = var(32) = 0
trigger1 = var(1) ;Use combo condition (above)

[State -1,  Light Kung Fu Blow];先行入力
type = VarSet
v = 29
triggerall = command = "QCF_x"
trigger1 = movetype = I
trigger1 = stateno = 101
trigger2 = movetype = I
trigger2 = stateno = 102
trigger3 = movetype = I
trigger3 = stateno = 106
trigger4 = movetype = I
trigger4 = stateno = 107
trigger5 = movetype = H
trigger5 = stateno = 5120
trigger5 = time > 6
value = 1100

[State -1,  Light Kung Fu Blow];先行入力
type = ChangeState
triggerall = var(29) = 1100
triggerall = var(32) = 0
trigger1 = stateno = 102
trigger1 = movetype = I
trigger1 = time > 2
trigger2 = stateno = 107
trigger2 = movetype = I
trigger2 = time > 2
trigger3 = stateno = 5120
trigger3 = movetype = H
trigger3 = animtime = 0
value = 1100


;---------------------------------------------------------------------------
[State -1, Light Kung Fu Palm]
type = ChangeState
value = 1110
triggerall = command = "QCF_y"
triggerall = var(32) = 0
trigger1 = var(1) ;Use combo condition (above)

[State -1,  Light Kung Fu Blow];先行入力
type = VarSet
v = 29
triggerall = command = "QCF_y"
trigger1 = movetype = I
trigger1 = stateno = 101
trigger2 = movetype = I
trigger2 = stateno = 102
trigger3 = movetype = I
trigger3 = stateno = 106
trigger4 = movetype = I
trigger4 = stateno = 107
trigger5 = movetype = H
trigger5 = stateno = 5120
trigger5 = time > 6
value = 1110

[State -1,  Light Kung Fu Blow];先行入力
type = ChangeState
triggerall = var(29) = 1110
triggerall = var(32) = 0
trigger1 = stateno = 102
trigger1 = movetype = I
trigger1 = time > 2
trigger2 = stateno = 107
trigger2 = movetype = I
trigger2 = time > 2
trigger3 = stateno = 5120
trigger3 = movetype = H
trigger3 = animtime = 0
value = 1110

;---------------------------------------------------------------------------
[State -1, Light Kung Fu Palm]
type = ChangeState
value = 1150
triggerall = command = "QCF_x"
triggerall = statetype = A
triggerall = var(34) = 0
trigger1 = ctrl
trigger2 = stateno = 1210
trigger2 = time > 7
trigger3 = stateno = 61

[State -1, Light Kung Fu Palm]
type = ChangeState
value = 1160
triggerall = command = "QCF_y"
triggerall = statetype = A
triggerall = var(34) = 0
trigger1 = ctrl
trigger2 = stateno = 1210
trigger2 = time > 7
trigger3 = stateno = 61

;---------------------------------------------------------------------------
[State -1, Light Kung Fu Palm]
type = ChangeState
value = 1500
triggerall = command = "step"
triggerall = statetype = A
trigger1 = ctrl
trigger2 = stateno = 1210
trigger2 = time > 7
trigger3 = stateno = 61

[State -1, Light Kung Fu Palm]
type = ChangeState
value = 1500
triggerall = command = "step"
triggerall = statetype = A
trigger1 = ctrl
trigger2 = stateno = 1210
trigger2 = time > 7
trigger3 = stateno = 61
trigger4 = stateno = 600
trigger4 = movecontact
trigger5 = stateno = 630
trigger5 = movecontact

[State -1, Light Kung Fu Palm]
type = ChangeState
value = 1500
triggerall = command = "step2"
triggerall = statetype = A
trigger1 = ctrl
trigger2 = stateno = 1210
trigger2 = time > 7
trigger3 = stateno = 61
trigger4 = stateno = 600
trigger4 = movecontact
trigger5 = stateno = 630
trigger5 = movecontact

;---------------------------------------------------------------------------
;Light Kung Fu Blow
[State -1, Light Kung Fu Blow]
type = ChangeState
value = 1000
triggerall = command = "QCB_x"
triggerall = statetype != A
triggerall = NumHelper(1001) = 0
trigger1 = ctrl;var(1) ;Use combo condition (above)

[State -1,  Light Kung Fu Blow];先行入力
type = VarSet
v = 29
triggerall = command = "QCB_x"
trigger1 = movetype = I
trigger1 = stateno = 101
trigger2 = movetype = I
trigger2 = stateno = 102
trigger3 = movetype = I
trigger3 = stateno = 106
trigger4 = movetype = I
trigger4 = stateno = 107
trigger5 = movetype = H
trigger5 = stateno = 5120
trigger5 = time > 6
value = 1000

[State -1,  Light Kung Fu Blow];先行入力
type = ChangeState
triggerall = var(29) = 1000
trigger1 = stateno = 102
trigger1 = movetype = I
trigger1 = time > 2
trigger2 = stateno = 107
trigger2 = movetype = I
trigger2 = time > 2
trigger3 = stateno = 5120
trigger3 = movetype = H
trigger3 = animtime = 0
value = 1000

;---------------------------------------------------------------------------
;Strong Kung Fu Blow
[State -1, Strong Kung Fu Blow]
type = ChangeState
value = 1002
triggerall = command = "QCB_y"
triggerall = statetype != A
triggerall = NumHelper(1001) = 0
trigger1 = ctrl;var(1) ;Use combo condition (above)

[State -1,  Light Kung Fu Blow];先行入力
type = VarSet
v = 29
triggerall = command = "QCB_y"
trigger1 = movetype = I
trigger1 = stateno = 101
trigger2 = movetype = I
trigger2 = stateno = 102
trigger3 = movetype = I
trigger3 = stateno = 106
trigger4 = movetype = I
trigger4 = stateno = 107
trigger5 = movetype = H
trigger5 = stateno = 5120
trigger5 = time > 6
value = 1002

[State -1,  Light Kung Fu Blow];先行入力
type = ChangeState
triggerall = var(29) = 1002
trigger1 = stateno = 102
trigger1 = movetype = I
trigger1 = time > 2
trigger2 = stateno = 107
trigger2 = movetype = I
trigger2 = time > 2
trigger3 = stateno = 5120
trigger3 = movetype = H
trigger3 = animtime = 0
value = 1002
;---------------------------------------------------------------------------
;Strong Kung Fu Blow
[State -1, Strong Kung Fu Blow]
type = ChangeState
value = 1200
triggerall = command = "warp"
trigger1 = var(1) ;Use combo condition (above)

;Strong Kung Fu Blow
[State -1, Strong Kung Fu Blow]
type = ChangeState
value = 1205
triggerall = command = "warp2"
trigger1 = var(1) ;Use combo condition (above)
;===========================================================================
;---------------------------------------------------------------------------
;Run Fwd
;ダッシュ
[State -1, Run Fwd]
type = ChangeState
value = 100
triggerall = command = "FF"
trigger1 = statetype = S
trigger1 = ctrl
trigger2 = stateno = 200 
trigger2 = movecontact
trigger3 = stateno = 230 
trigger3 = movecontact

[State -1, Run Fwd];先行入力
type = VarSet
v = 29
triggerall = command = "FF"
triggerall = movetype = A
trigger1 = stateno = 240 
trigger1 = movecontact
trigger1 = time > 6
trigger2 = stateno = 410 
trigger2 = movecontact
trigger2 = time > 6
trigger3 = stateno = 210 
trigger3 = movecontact
trigger3 = time > 6
value = 100

[State -1, Run Fwd];先行入力
type = ChangeState
triggerall = var(29) = 100
triggerall = movetype = A
trigger1 = stateno = 240 
trigger1 = time > 8
trigger2 = stateno = 410 
trigger2 = time > 8
trigger3 = stateno = 210 
trigger3 = time > 7
value = 100

;---------------------------------------------------------------------------
;Run Back
;後退ダッシュ
[State -1, Run Back]
type = ChangeState
value = 105
triggerall = command = "BB"
trigger1 = statetype = S
trigger1 = ctrl
trigger2 = stateno = 200 
trigger2 = movecontact
trigger3 = stateno = 230 
trigger3 = movecontact

[State -1,  Run Back];先行入力
type = VarSet
v = 29
triggerall = command = "BB"
triggerall = movetype = A
trigger1 = stateno = 240
trigger1 = movecontact
trigger1 = time > 6
trigger2 = stateno = 410
trigger2 = movecontact
trigger2 = time > 6
trigger3 = stateno = 210 
trigger3 = movecontact
trigger3 = time > 6
value = 105

[State -1,  Run Back];先行入力
type = ChangeState
triggerall = var(29) = 105
triggerall = movetype = A
trigger1 = stateno = 240 
trigger1 = time = 8
trigger2 = stateno = 410 
trigger2 = time = 8
trigger3 = stateno = 210 
trigger3 = time > 7
value = 105


;===========================================================================
;特殊技スライディング
[State -1, Crouching Strong Kick]
type = ChangeState
value = 650
triggerall = command = "a"
triggerall = command = "holdfwd"
trigger1 = statetype = S
trigger1 = ctrl
trigger2 = stateno = 230
trigger2 = time > 4
trigger2 = movecontact
trigger3 = stateno = 200
trigger3 = time > 4
trigger3 = movecontact
trigger4 = stateno = 52

[State -1,  Light Kung Fu Blow];先行入力
type = VarSet
v = 29
triggerall = command = "a"
;triggerall = command = "holddown"
triggerall = command = "holdfwd"
trigger1 = movetype = I
trigger1 = stateno = 101
trigger5 = time > 6
value = 652

[State -1,  Light Kung Fu Blow];先行入力
type = ChangeState
triggerall = var(29) = 652
trigger1 = stateno = 102
trigger1 = movetype = I
trigger1 = 1
value = 652

;---------------------------------------------------------------------------
;Stand Light Punch
;立ち弱パンチ
[State -1, Stand Light Punch]
type = ChangeState
value = 200
triggerall = command = "x"
triggerall = command != "holddown"
trigger1 = statetype = S
trigger1 = ctrl
trigger2 = stateno = 200
trigger2 = time > 6
trigger3 = stateno = 52

;---------------------------------------------------------------------------
;Stand Strong Punch
;立ち強パンチ
[State -1, Stand Strong Punch]
type = ChangeState
value = 210
triggerall = command = "y"
triggerall = command != "holddown"
trigger1 = statetype = S
trigger1 = ctrl
trigger2 = (stateno = 200) && time > 5
trigger3 = (stateno = 230) && time > 8
trigger4 = stateno = 52

;---------------------------------------------------------------------------
;Stand Light Kick
;立ち弱キック
[State -1, Stand Light Kick]
type = ChangeState
value = 230
triggerall = command = "a"
triggerall = command != "holddown"
trigger1 = statetype = S
trigger1 = ctrl
trigger2 = (stateno = 200) && time > 7
trigger3 = (stateno = 230) && time > 7
trigger3 = movecontact
trigger4 = stateno = 52

;---------------------------------------------------------------------------
;Standing Strong Kick
;立ち強キック
[State -1, Standing Strong Kick]
type = ChangeState
value = 240
triggerall = command = "b"
triggerall = command != "holddown"
trigger1 = statetype = S
trigger1 = ctrl
trigger2 = (stateno = 200) && time > 7
trigger3 = (stateno = 230) && time > 7
trigger3 = movecontact
trigger4 = stateno = 52

;---------------------------------------------------------------------------
;Crouching Light Punch
;しゃがみ弱パンチ
[State -1, Crouching Light Punch]
type = ChangeState
value = 400
triggerall = command = "x"
triggerall = command = "holddown"
trigger1 = statetype = C
trigger1 = ctrl
trigger2 = stateno = 400
trigger2 = time > 6
trigger2 = movecontact
trigger3 = stateno = 430
;trigger3 = time > 6
trigger3 = movecontact
trigger4 = stateno = 52
;---------------------------------------------------------------------------
;Crouching Strong Punch
;しゃがみ強パンチ
[State -1, Crouching Strong Punch]
type = ChangeState
value = 410
triggerall = command = "y"
triggerall = command = "holddown"
trigger1 = statetype = C
trigger1 = ctrl
trigger2 = stateno = 400
trigger2 = time > 6
trigger2 = movecontact
trigger3 = stateno = 430
trigger3 = time > 6
trigger3 = movecontact
trigger4 = stateno = 52
;---------------------------------------------------------------------------
;Crouching Light Kick
;しゃがみ弱キック
[State -1, Crouching Light Kick]
type = ChangeState
value = 430
triggerall = command = "a"
triggerall = command = "holddown"
trigger1 = statetype = C
trigger1 = ctrl
trigger2 = stateno = 400
trigger2 = time > 6
trigger2 = movecontact
trigger3 = stateno = 430
trigger3 = time > 6
trigger3 = movecontact
trigger4 = stateno = 52
;---------------------------------------------------------------------------
;Crouching Strong Kick
;しゃがみ強キック
[State -1, Crouching Strong Kick]
type = ChangeState
value = 440
triggerall = command = "b"
triggerall = command = "holddown"
trigger1 = statetype = C
trigger1 = ctrl
trigger2 = stateno = 430
trigger2 = time > 4
trigger2 = movecontact
trigger3 = stateno = 400
trigger3 = time > 4
trigger3 = movecontact
trigger4 = stateno = 52
;---------------------------------------------------------------------------
;Jump Light Punch
;空中弱パンチ
[State -1, Jump Light Punch]
type = ChangeState
value = 600
triggerall = command = "x"
trigger1 = statetype = A
trigger1 = ctrl
trigger1 = stateno != 600
trigger2 = stateno = 1350 ;Air blocking
trigger3 = stateno = 1210
trigger3 = time > 7
trigger4 = stateno = 61
;---------------------------------------------------------------------------
;Jump Strong Punch
[State -1, Jump Strong Punch]
type = ChangeState
value = 610
triggerall = command = "y"
trigger1 = statetype = A
trigger1 = ctrl
trigger2 = stateno = 600 || stateno = 630 ;jump_x or jump_a
trigger2 = movecontact
trigger3 = stateno = 1350 ;Air blocking
trigger4 = stateno = 1210
trigger4 = time > 7
trigger5 = stateno = 61
;---------------------------------------------------------------------------
;Jump Light Kick
[State -1, Jump Light Kick]
type = ChangeState
value = 630
triggerall = command = "a"
trigger1 = statetype = A
trigger1 = ctrl
trigger2 = stateno = 1350 ;Air blocking
trigger3 = stateno = 1210
trigger3 = time > 7
trigger4 = stateno = 61
;---------------------------------------------------------------------------
;Jump Strong Kick
;空中強キック
[State -1, Jump Strong Kick]
type = ChangeState
value = 640
triggerall = command = "b"
trigger1 = statetype = A
trigger1 = ctrl
trigger2 = stateno = 1350 ;Air blocking
trigger3 = stateno = 1210
trigger3 = time > 7
trigger4 = stateno = 61
;----------------------------------
[State -1, Run Back]
;ハイジャンプ
type = ChangeState
value = 115
triggerall = command = "HJ"
trigger1 = statetype != A
trigger1 = ctrl




